add delete subgraph functionality [WIP]
flux-framework/flux-sched pull request #1053
Opened 2023-07-27 15:52 UTC by zekemorton

This PR adds delete subgraph functionality to the jgf reader and resource query. This is a part of the elasticity effort and allows removal of a piece of the resource graph. This function works by passing in a path of a node in the graph (ex /medium0/rack3) and will remove the tree with that node as root (ex /medium0/rack3/*). 

This implementation requires two main steps. The first step is to identify all boost graph nodes in the subgraph. This is done via a DFS on the out edges of each node. Note that one of the out edges of a node is its parent, so in this case a string comparison of the path was used to determine that an out edge is not the parent. The second step is to remove the nodes from the graph. Because we are using listS instead of vecS, actually deleting the nodes would invalidate the vertex descriptors, which would invalidate the resource graph metadata used for vertex descriptor look ups. Instead, this PR clears all edges from "deleted nodes" and removes them from the resource graph metadata. This makes them unaccessible from traversals from the main graph and unaccessible from resource graph metadata look ups. 

This PR also adds this functionality to resource query and adds new tests for these features. 

WIP to do items:

- [ ] Add automated tests for remove subgraph

2023-07-27 20:40 UTC, zekemorton commented on resource/readers/resource_reader_jgf.cpp
> +            if (paths_it.second.find(g[node].name) !=std::string::npos &&
Add a comment to explain this check

2023-08-21 17:59 UTC, milroy requested changes
This is looking very good. After you fix a few nits and typos and address one question this should be good to merge. Thanks a lot!

2023-08-21 17:59 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +                get_subgraph_nodes(g, next_node, node_list);
```suggestion
            if (paths_it.second.find (g[node].name) != std::string::npos &&
                paths_it.second.find (g[node].name) < paths_it.second.find (g[next_node].name)) {

                node_list.push_back (next_node);
                get_subgraph_nodes (g, next_node, node_list);
```

2023-09-20 23:02 UTC, zekemorton commented
After finding a segfault centered around not deleting elements from the by_outedge member of the resource graph metadata, I added in a few new changes to solve this issue. 
 - remove the by_outedge for each vertex that we remove from the resource graph
 - remove any edges from the vertex who is parent to the root of the removed subgraph to the root vertex (note that there can be more than one)
 - add in tests that try to fully allocate the resource graph after removing a resource

2023-09-20 23:24 UTC, jameshcorbett commented
> After finding a segfault

Pincer maneuver complete

2023-09-21 20:26 UTC, milroy commented on resource/utilities/command.cpp
> +        std::cerr << "ERROR: can't reinitialize traverser after remove"
Let's remove this `initialize` call now because it corrupts `idata` planners. See issue #1075 .

2023-09-25 16:27 UTC, zekemorton commented
@milroy I add the most recent changes requested including the two TODO messages and spacing fixes. 
I am not sure what the issue is with the python version tests though. Any thoughts there?

2023-09-27 08:29 UTC, milroy commented
Looks like you figured out the runner issue with PR #1080. I'm approving this PR, but let's wait to merge it until #1080 is merged.

2023-09-27 08:30 UTC, milroy approved these changes
Thanks for the changes! LGTM.

2023-09-28 07:26 UTC, milroy commented
@zekemorton since PR #1080 is merged you can rebase this PR and set MWP.

2023-09-28 17:16 UTC, zekemorton commented
> Approving reviews have been dismissed because this pull request was updated.

@milroy looks like it might need another approval since doing the rebase

2023-09-28 20:52 UTC, milroy approved these changes
Approving again in the hopes that this will trigger MWP action.

2023-09-28 20:53 UTC, merged