Add first nodex policy
flux-framework/flux-sched pull request #1055
Opened 2023-08-02 23:58 UTC by trws

First cut to add a node exclusive first policy.  This seems to work, refactored one of the nodex tests to not be quite so duplicative and test this too.  In cases with no overlapping jobs, firstnodex is the same as hinodex, but it will only look for one match rather than scoring matches.

Need to test the performance, but this should be significantly faster than the other nodex policies.

2023-08-03 20:22 UTC, trws commented
Looking at the code for this, I'm thinking it would be really useful to add a new "policy" that lets us build one of these up more dynamically. It would let us factor out duplication here and let us play with the number of matches to look for and things like that.  I kinda want to get this in so we _have_ it, then build that up.

2023-08-03 20:48 UTC, trws commented
Rebased.

2023-08-04 00:14 UTC, trws commented
Quick resource-bench.sh numbers:

```
firstnodex
Min. Match Time: 1.90735e-06
Max. Match Time: 0.000230789
Avg. Match Time: 0.000187913
first
Min. Match Time: 6.60419e-05
Max. Match Time: 0.000261068
Avg. Match Time: 9.12583e-05
hinodex
Min. Match Time: 1.90735e-06
Max. Match Time: 0.0184488
Avg. Match Time: 0.00863134
```

So, firstnodex is about 450 times faster than hinodex, but still about 10x slower than first, at least for this little microbenchmark.

2023-08-25 01:48 UTC, milroy requested changes
This looks good overall and is an elegant implementation. I did find a few things that need to be changed, which I indicated in the line-specific comments. 

Two other higher-level changes:
1. Please add `firstnodex` and description here: https://github.com/flux-framework/flux-sched/blob/76f2e3bf0e5698bd0a9821f6e2392a1d91706e59/resource/utilities/resource-query.cpp#L126
2. Please break up the commit such that there is one for "policies" (changes to `dfu_match_policy_factory.*pp`, "testsuite" (changes to `t3033-resoure-nodex.t`), and "resource-query" (changes to `resource-query.cpp`).

2023-08-25 01:48 UTC, milroy commented on resource/policies/dfu_match_policy_factory.cpp
>      std::shared_ptr<dfu_match_cb_t> matcher = nullptr;
Please add a description to the body of the commit following the Flux "Problem:, Add:" convention.

2023-08-25 01:48 UTC, milroy commented on resource/policies/dfu_match_policy_factory.cpp
> +               ptr->add_exclusive_resource_type ("node");
I'm really impressed that this is all it takes to generate the correct behavior!

2023-08-25 01:48 UTC, milroy commented on t/t3033-resource-nodex.t
> +
I like that this function reduces duplicate code.

2023-08-25 01:48 UTC, milroy commented on t/t3033-resource-nodex.t
> +run_tests_with_policy firstnodex 00
I tested the outputs in the `jammy` container and can reproduce the results comparing the output to `hinodex`. I don't think there's a guarantee `firstnodex` will always select the same resources as `hinodex`.

2023-08-25 06:59 UTC, milroy commented on t/t3033-resource-nodex.t
> +run_tests_with_policy firstnodex 00
That said, it's no different than how the current `first` policy check works in `t3001-resource-basic.t`.

2023-08-26 02:22 UTC, trws commented on resource/policies/dfu_match_policy_factory.cpp
> +               ptr->add_exclusive_resource_type ("node");
Much as the current traverser is really complex, this is why.  Dong designed it to be amazingly flexible and generic.  Hopefully we can take a bit better advantage of that if we expose it a bit more.

2023-09-01 22:49 UTC, trws commented
It ended up being four commits, because I decided to convert the usage message string into a C++11 raw string and made that a separate commit.  This should be good to go unless I botched something in rebasing it.

2023-09-05 04:31 UTC, milroy approved these changes
Thanks for the reorganization!

There's a spacing issue that your editor introduced on one line. Please fix the alignment because it makes the block slightly confusing.

2023-09-05 04:31 UTC, milroy commented on resource/utilities/resource-query.cpp
> +    ctx->db = std::make_shared<resource_graph_db_t> ();
Looks like VScode messed up the spacing here.

2023-09-06 19:57 UTC, merged