Add a set-status RPC for marking vertices up or down
flux-framework/flux-sched pull request #1110
Opened 2023-12-02 06:01 UTC by jameshcorbett

The motivation for this PR comes from [this flux-coral2 issue](https://github.com/flux-framework/flux-coral2/issues/99). Rabbits can (and very often do) go down, and fluxion needs to avoid scheduling rabbit jobs on dead rabbits. Rabbit status is monitored by HPE software and reported in kubernetes objects, which flux-coral2 software checks. The flux-coral2 software needs a way to report to Fluxion that a rabbit has died (or resurrected).

This PR provides a way to do that. Flux-coral2 can now send a RPC like `sched-fluxion-resource.set_status /path/to/rabbit down` to mark a rabbit as down, and similarly to mark it up.

However, I did notice that marking all the nodes or racks in the resource graph didn't prevent jobs from running, hence the test failures. @milroy do you know whether this is expected? Is marking a resource as 'down' purely informational--does it have no effect on actual resource choices?

As an aside, one tricky aspect is that with this PR, flux-coral2 will need to know the resource graph layout. It will know the hostname of the rabbit that has gone down, but it won't necessarily know that the rabbit 'rzvernal201' is '/rzvernal/rack3/rzvernal201` in the resource graph. I think I can work around this though--the resource graph is already written out to a file (because it needs to contain information about rabbit locality) so the flux-coral2 software can read in that graph and figure things out.

2023-12-05 15:37 UTC, jameshcorbett commented
@grondo can you describe what the core-sched interactions are when a node goes down?

2023-12-05 17:44 UTC, jameshcorbett commented
Thanks @grondo , that actually gave me the information I needed to fix the tests! I think this PR is a pretty harmless addition now.

2023-12-06 22:16 UTC, zekemorton approved these changes
I looked through all of the commits, and the code looks clean and all of the changes make sense! I couldn't find anything to complain about. 

I think it's still a good idea for @milroy to give it a look over

2023-12-12 09:04 UTC, milroy commented
I'll add my review today.

2023-12-12 17:51 UTC, milroy requested changes
This PR is almost ready to merge. I'm requesting a quick change to remove duplicate code and it will be ready to merge.

2023-12-12 17:51 UTC, milroy commented on resource/modules/resource_match.cpp
> +        if (flux_respond_error (h, msg, EINVAL, errmsg.c_str()) < 0)
Nit: spacing.
```suggestion
        if (flux_respond_error (h, msg, EINVAL, errmsg.c_str ()) < 0)
```

2023-12-12 17:51 UTC, milroy commented on resource/modules/resource_match.cpp
> +        if (flux_respond_error (h, msg, EINVAL, errmsg.c_str()) < 0)
Nit: spacing.
```suggestion
        if (flux_respond_error (h, msg, EINVAL, errmsg.c_str ()) < 0)
```

2023-12-12 17:51 UTC, milroy commented on resource/modules/resource_match.cpp
> +        return;
You could save the repetition of the `flux_respond_error` and `flux_log_error` by setting `errmsg` and using `goto error` like this block: https://github.com/flux-framework/flux-sched/blob/0b70113bdf7eef5d501815d50155bdf124b14bae/resource/modules/resource_match.cpp#L1863

```suggestion
        errmsg = "malformed RPC";
        goto error;
```
That would apply to the following blocks, too.

2023-12-12 18:15 UTC, jameshcorbett commented on resource/modules/resource_match.cpp
> +        return;
I originally wrote this function that way, but the compiler complained that I was jumping over the initialization of some variables, and so it prevented me from using the `auto` type. Do you have any recommendations to avoid that?

2023-12-12 18:35 UTC, milroy commented on resource/modules/resource_match.cpp
> +        return;
I've run into that a lot, too. You'll need to declare the variable before the `if` blocks. Sometimes that isn't feasible; if that's true in this case then we can merge this PR.

2023-12-12 20:45 UTC, jameshcorbett commented on resource/modules/resource_match.cpp
> +        return;
Done! And your spacing comments addressed.

2023-12-12 21:39 UTC, milroy approved these changes

2023-12-12 21:40 UTC, milroy commented
LGTM! Approved.

Once you rebase against the current `master` you can set MWP.

2023-12-12 21:42 UTC, jameshcorbett commented
Done, setting MWP. Thanks @milroy !

2023-12-12 21:51 UTC, merged