Add match options and match satisfy to reapi [WIP]
flux-framework/flux-sched pull request #1133
Opened 2024-01-09 22:49 UTC by zekemorton

This PR adds changes to the different bindings for the reapi. These changes center around how match allocate was originally implanted for both the cli and the module. In both bases, the only options are to use either "allocate_orelse_reserve" or "allocate".

This PR introduces 2 new functions to the bindings for go and C and overloads the match allocate function for c++. 

C/Go:
Added functions Match and MatchSatisfy. 
Match is the general purpose match function that interfaces with the C++ bindings
MatchSatisfy is a new function that wraps Match using the "satisfiability" option. 
MatchAllocate is now a wrapper to Match that converts the orelse_reserve bool into the appropriate match option.

C++: 
Added an overloaded match allocate function that acts much like Match as mentioned above.
Edited match allocate to like mentioned above.

2024-01-09 23:08 UTC, vsoch reviewed
Did a quick review!

2024-01-09 23:08 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +// Match matches a jobspec to the "best" resources and either allocate
```suggestion
// MatchAllocate matches a jobspec to the "best" resources and either allocate
```

2024-01-09 23:08 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +// Match matches a jobspec to the "best" resources and either allocate
And looks like the parameters / returns need to be updated.

2024-01-09 23:08 UTC, vsoch commented on resource/reapi/bindings/c/reapi_module.h
> + *  \param cmd       const char *: set to specify the specific match option
"cmd" for a job / workload manager might be confusing - perhaps just explicitly call this `match_option` or similar.

2024-01-09 23:08 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +	if orelse_reserve {
These should be const defined by the module at the top.

2024-01-09 23:08 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxmodule/reapi_module.go
> +	if orelse_reserve {
Ditto.

2024-01-09 23:08 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxmodule/reapi_module.go
> +	cmd := "satisfiability"
Constant here as well.

2024-01-25 00:30 UTC, zekemorton commented
@vsoch @milroy I think this one is finally ready for another review! Let me know what you think or if you have any questions

2024-01-25 02:04 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxmodule/reapi_module.go
> +const (
Ditto here.

2024-01-25 02:04 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxmodule/reapi_module.go
> +func (m *ReapiModule) MatchSatisfy(
I have a dumb question - I've never used the module (only the client) - what's the difference, and how does that lead to the different designs for the (equivalently named) functions here? What I'm wanting to understand is if this is something we should be aiming to maintain similar interfaces for (or not).

2024-01-25 02:04 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +	return cli.Match(match_op, jobspec)
I like this!

2024-01-25 02:04 UTC, vsoch commented on resource/reapi/bindings/go/src/test/main.go
> +		fmt.Printf("Error in ReapiClient MatchAllocate: %v\n", err)
Just to sanity check out tests here (I haven't looked in a while) does a return ensure there is a test failure? Or the design is just based on the output (and we don't need to check for failure because the output would be wrong, that would make sense too).

2024-01-25 02:04 UTC, vsoch commented on t/data/resource/expected/rq2/003.R.out
> +      ---------node1[1:s]
Yes, operator, I'd like my new wallpaper in "flux R output" design. Yes, extra squiggles please.

2024-01-28 09:20 UTC, milroy requested changes
Adding a change request to resolve the item with CamelCase.

Beyond a few nits and typos this looks really good to me. In particular I like your API design with overloads to maintain backwards compatibility. It may be possible to use an interface instead, though.

@trws, do you have a preference or another design suggestion here?

2024-01-28 09:20 UTC, milroy commented on resource/reapi/bindings/c/reapi_cli.h
> + *  the selected match policy.
Typo in description:
```suggestion
/*! Run Satisfiability check for jobspec. 
```

2024-01-28 09:20 UTC, milroy commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +	return cli.Match(match_op, jobspec)
Agreed!

2024-01-28 09:20 UTC, milroy commented on resource/reapi/bindings/go/src/fluxmodule/reapi_module.go
> +func (m *ReapiModule) MatchSatisfy(
The module is designed to send RPCs to and receive responses from Fluxion (running in a Flux instance) rather than start/stop/maintain a context. It would be useful to maintain similar interfaces because it may be fun to try wiring up multiple module clients to the same Flux + Fluxion instance. Like if we wanted to maintain coherent scheduling state between Flux resources (e.g., on bare metal) and Fluence resources.

2024-01-28 09:20 UTC, milroy commented on resource/reapi/bindings/go/src/fluxmodule/reapi_module.go
> +func (m *ReapiModule) MatchSatisfy(
(The module is what Flux uses to call procedures in Fluxion.)

2024-01-28 17:36 UTC, trws commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc == 0) && (match_op != match_op_t::MATCH_SATISFIABILITY)) {
If it needs a pre-space, doesn’t it need a post-space also? Is this what gofmt would output?

2024-01-28 17:37 UTC, trws commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc == 0) && (match_op != match_op_t::MATCH_SATISFIABILITY)) {
Bah, not go, sorry.  Still the symmetric spacing point stands.

2024-01-28 17:38 UTC, trws commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
This whole function shows up as untested.

2024-01-28 17:42 UTC, trws commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
Could we pass the match_op_t enum rather than a string around?  Using all the strcmps to turn it back into an enum seems a bit painful.  Maybe a helper function to convert the string to enum if we need to do that elsewhere then pass it through?

2024-01-28 17:47 UTC, trws commented
I think I’m generally ok here, would strongly prefer that we avoid stringly-typed interfaces where we can, but the general design seems like a notable improvement in how we can grow the interface so that’s great.

2024-01-28 18:57 UTC, vsoch commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
I also really like the idea of enums. I haven't used them in cgo yet, but they seem fairly straight forward. @zekemorton here is an example: https://github.com/giorgisio/cgo/blob/master/enums.go. If we have enums for the match options instead of strings, of course no need to worry about camel case.

2024-01-29 17:43 UTC, zekemorton commented on resource/reapi/bindings/go/src/test/main.go
> +		fmt.Printf("Error in ReapiClient MatchAllocate: %v\n", err)
The design us just based on the output, so it compares what running it prints out compared to a file of expected output.

2024-01-29 19:13 UTC, vsoch commented on resource/reapi/bindings/go/src/test/main.go
> +		fmt.Printf("Error in ReapiClient MatchAllocate: %v\n", err)
yeah - I remembered this shortly after I commented (and updated my comment). Thanks for the reminder!

2024-01-30 00:44 UTC, zekemorton commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
I think that makes a lot of sense! I can change the C bindings cli to use to use enum as a parameter for match op. Do you think I should also change the go bindings to use enum? I wasn't sure if we wanted to use any C types for the go function parameters? Is there a go specific version of an enum that might work better here?

2024-01-30 00:51 UTC, zekemorton commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
Yes, I am not sure what the best way to add tests for this is. This function was added for backwards compatibility reasons, but the other changes in this PR seem to move at least what is tested away from it. I am not sure if there is anything using this function directly with the c++ bindings or if it would be safe to remove or not.

2024-01-30 03:38 UTC, vsoch commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
I'm not sure, because there isn't technically an enum type in Go, but we do have iota and constants! Let me mess around a bit tonight and put together an idea or proposal.

2024-01-30 06:35 UTC, vsoch commented
@zekemorton @trws @milroy I put together a quick prototype for what I think might be a good pattern for adding the faux enum, and also testing it: https://github.com/zekemorton/flux-sched/pull/1

The problem and summary are in the description there, and I'll provide some bullets here.

## Organization

- I think we will eventually want to move shared logic between reapi_cli and reapi_module into a common place. The convention for that in go is a "pkg" directory so I added that to src.

## Enum Design

- Reading about enum types, the most widely accepted (but not loved, overall, people are not happy there is no native type) is to use iota with const. A slight detail I picked up on is having an indicator for "we forgot to set this" - so instead of MatchAllocate being 0, we set MatchUnknown to 0.
- The other pattern I saw was for human readability, and that is having a String() function so if someone passes this new `MatchType` to a fmt as a string, it will not throw an error.

## Testing

This was a bit hard. I started with a strategy that would (akin to build) generate a binary, but (to be frank) I don't like the complexity of this approach. We should not need to have CMakeLists.txt and Makefile.am in _every_ single go package directory with a `something_test.go` forever on out. Instead, I want to start on the premise that when a pkg is imported into a main function (e.g., into the main test directory) it would be used (and thus tested, as a binary) there. And then to supplement that, I want to do the vanilla, expected setup that you see with go - a run of `go test -v`. So that's the [test that I added](https://github.com/researchapps/flux-sched/blob/1c0570eea5a0ce0548928641efdd7a8b9d6d8c75/t/t9001-golang-basic.t#L38-L43). The start of that file checks for go on the path, so we already know we have it. The test assumes that the test itself is run in a subshell (so any changes of directory are essentially thrown away).

If we like this design, I can detail the next steps. The main step is to add the enum to C, and then to integrate the types module into each of the reapi module and cli.  Instead of adding it (I am bad/slow at C) I include an example (and example usage) [here](https://github.com/researchapps/flux-sched/blob/1c0570eea5a0ce0548928641efdd7a8b9d6d8c75/resource/reapi/bindings/go/src/pkg/types/types.go#L13-L26). In addition to the [tests that I wrote](https://github.com/researchapps/flux-sched/blob/go-enum-prototype-with-test/resource/reapi/bindings/go/src/pkg/types/types_test.go) we likely would want to have tests that sanity check the C enums in some way against Go to make sure we don't mess them up.

Finally, we could likely add some nice helper functions to that, to assist with the conversion of checking if something is a type (e.g., it would be easier to call `mt.IsMatchAllocate()` and get a boolean vs. something else.

2024-01-31 00:24 UTC, milroy commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
This function will get tested once we move to the new `resource-query` (`rq2`) that Zeke is developing. `rq2` is a client of REAPI CLI, so we'll get coverage testing via the testsuite.

2024-01-31 00:41 UTC, zekemorton commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
rq2 is already represented in the test suite, at least in regards to match_allocate. The match allocate referenced above uses the orelse_reserve flag rather that the match_op parameter. It's possible that it can be safely removed if rq2 and reapi c bindings are the only clients of reapi c++ bindings, though I am not sure if that is the case.

2024-01-31 01:49 UTC, milroy commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
Got it. I don't know of any other reapi C++ clients.

2024-01-31 15:12 UTC, trws commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
AFAIK the best you can do is a newtype-like thing with say `type MatchType int` or similar, then make a set of constants based on that, or re-use the C ones maybe by re-exporting their names from the module.  Either way, I'd say ensure that the values in go are taken from C automatically if possible, just to keep maintenance low.

2024-01-31 18:09 UTC, vsoch commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
lol, like this?

https://github.com/researchapps/flux-sched/blob/1c0570eea5a0ce0548928641efdd7a8b9d6d8c75/resource/reapi/bindings/go/src/pkg/types/types.go#L31-L40

![image](https://github.com/flux-framework/flux-sched/assets/814322/c10c6946-9fab-48c5-9d8e-4c48d6cecb6a)

2024-01-31 18:10 UTC, vsoch commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
Side note - did that two days ago - [full PR here](https://github.com/researchapps/flux-sched/commit/f16741eee8b5ca427fbc75579bea4334ded70848). I think everyone missed it here. I want to again emphasize that we need a setup that 1. introduces more modular (shared) types / components, and 2. allows for standard go style testing and 3. makes a distinction between the variable being undefined and the first type.

2024-01-31 18:15 UTC, vsoch commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
I'm happy to follow up with a PR for whichever of those features are out of scope here.

2024-01-31 21:12 UTC, zekemorton commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
Yeah, I think would prefer a follow on PR with the conversion to enum if possible. I have a couple of things that I think take higher priority in the near term and would like to get this merged since it's a blocker for some of the things @vsoch has been working on

2024-02-01 00:31 UTC, zekemorton commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
Then should I remove it? This would remove the need for overloading the function in the first place which might be better in the long run

2024-02-02 01:15 UTC, zekemorton commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
After a hack session with @milroy I was able to convert the C and C++ bindings to use enum and adding in the changes for golang should hopefully be pretty smooth. I'll hack on it a bit and see if it can fall under the scope of this PR

2024-02-02 17:56 UTC, zekemorton commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +int reapi_cli_t::match_allocate (void *h, bool orelse_reserve,
I removed this function from the cli c++ bindings but kept it for the module c++ bindings since it seems its was being used by the queue manager.

2024-02-06 22:44 UTC, zekemorton commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                   const char *match_op, const char *jobspec,
Just added a new commit with some work in progress on using the interface with enums. I am running into what I think is a linking error during the build process with the go bindings. I'd love a second set of eyes on it if anyone gets a chance. The error I am getting is: 

```
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/tce/packages/gcc/gcc-10.3.1/bin/ld: /usr/tce/packages/gcc/gcc-10.3.1/bin/ld: DWARF error: could not find variable specification at offset 55654
/usr/tce/packages/gcc/gcc-10.3.1/bin/ld: DWARF error: could not find variable specification at offset 4a4d
...
/usr/tce/packages/gcc/gcc-10.3.1/bin/ld: DWARF error: could not find variable specification at offset 4ffd0
/g/g0/morton30/flux/flux-sched/resource/reapi/bindings/libreapi_cli.a(reapi_cli.cpp.o): in function `Flux::resource_model::detail::resource_query_t::traverser_run(Flux::Jobspec::Jobspec&, match_op_t, long, long&)':
/g/g0/morton30/flux/flux-sched/resource/reapi/bindings/c++/reapi_cli_impl.hpp:725: undefined reference to `Flux::resource_model::dfu_traverser_t::run(Flux::Jobspec::Jobspec&, std::shared_ptr<Flux::resource_model::match_writers_t>&, match_op_t, long, long*)'
collect2: error: ld returned 1 exit status

2024-02-06 23:43 UTC, vsoch commented on resource/reapi/bindings/go/src/test/CMakeLists.txt
okay here is what has worked for me:

```
# GOOS=linux CGO_CFLAGS="-I/home/flux-sched/resource/reapi/bindings/c" CGO_LDFLAGS="-L/usr/lib -L/home/flux-sched/resource -lresource -L/home/flux-sched/resource/libjobspec -ljobspec_conv -L/home/flux-sched/resource/reapi/bindings -lreapi_cli -lflux-idset -lstdc++ -lczmq -ljansson -lhwloc -lboost_system -lflux-hostlist -lboost_graph -lyaml-cpp" go build -ldflags '-w' -o bin/server cmd/main.go

BUILDENVVAR=CGO_CFLAGS="-I${FLUX_SCHED_ROOT}/resource/reapi/bindings/c" CGO_LDFLAGS="-L${INSTALL_PREFIX}/lib -L${FLUX_SCHED_ROOT}/resource -lfluxion-resource -L${FLUX_SCHED_ROOT}/resource/libjobspec -ljobspec_conv -L/${FLUX_SCHED_ROOT}/resource/reapi/bindings -lreapi_cli -lflux-idset -lstdc++ -lczmq -ljansson -lhwloc -lboost_system -lflux-hostlist -lboost_graph -lyaml-cpp"
```
The order matters too I think. And what about changing this line?

```
set(CGO_CFLAGS "-I${CMAKE_BINARY_DIR}/resource/reapi/bindings/c")
```
This step makes me run into trouble too, and what I usually do is figure out which symbol it is asking for, where it is being asked for from, and then 1. ensure that I'm adding that to the include or linked library path, and 2. ensure the order is correct so the thing needed is in the command string before where it's needed, if that makes sense.

2024-02-06 23:44 UTC, vsoch commented on resource/reapi/bindings/go/src/test/CMakeLists.txt
And then it's like, 20-30 minutes of trying random things until it works! :laughing:

2024-02-06 23:45 UTC, vsoch commented on resource/reapi/bindings/go/src/test/CMakeLists.txt
From a quick glance I think you'd want `-lreapi_cli` later, to come after the dependencies that it needs.

2024-02-07 02:03 UTC, trws commented on resource/reapi/bindings/go/src/test/CMakeLists.txt
> the thing needed is in the command string before where it's needed

Quick warning here, if this is a normal gcc-style command line, things earlier on the line can link to symbols provided by libraries and objects later on the line.  Writing that down it sounds backwards, but it is true.

2024-02-07 02:05 UTC, vsoch commented on resource/reapi/bindings/go/src/test/CMakeLists.txt
Note that @milroy just [pushed an update](https://github.com/flux-framework/flux-sched/blob/6b23d0d3502ae715f7aef165253024a9ba3d430d/resource/reapi/bindings/go/src/test/CMakeLists.txt) to his PR for the bindings that might help here too (I'm testing it out locally with flex-ice-cream, just waiting for the container environment to boot up)!

2024-02-08 02:14 UTC, zekemorton commented
Alright, I just pushed some changes and now it seems to build correctly and passes the test! 
I am not so familiar with CMake so I might have done something silly, but seems to be working. Let me know what you think!

2024-02-08 02:14 UTC, zekemorton commented on resource/reapi/bindings/go/src/test/CMakeLists.txt
Thanks so much for the tips here, this helped a lot!

2024-02-09 00:36 UTC, zekemorton commented
I just rebased and pushed changes that take advantage of @milroy 's recent PR. The cmake build commit should be a bit cleaner. This should now be ready for another review

2024-02-09 04:01 UTC, vsoch commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +	spec := C.CString(jobspec)
I think for `C.CString` it expects us (the developer) to free the memory, but [I'm not sure](https://groups.google.com/g/golang-nuts/c/bBylU8kE5uk/m/DFC3FvZTDH0J)

![image](https://github.com/flux-framework/flux-sched/assets/814322/70064397-f809-4f7e-82cd-ed8d5ea691f8)

Ping @trws I always get this wrong.

2024-02-09 04:02 UTC, vsoch commented
I forgot the most important thing! :bird: :exploding_head: 

![image](https://github.com/flux-framework/flux-sched/assets/814322/30a89ca6-5521-45fc-9067-36b72fced2da)

2024-02-09 17:01 UTC, vsoch commented
And to discuss some planning, I'm hoping to start work on moving the go bindings out of tree after we are merged here, and after that continue work on fluence. I'm going to start from the same git history and be very careful to rename / move so that the original authors / commits are preserved. It would be really great if we could finish this one up today (and then I could work over the weekend) but if that's not possible it's ok too.

2024-02-10 09:27 UTC, milroy requested changes
This is getting close and just requires a few formatting fixes and an additional guard check for a `match` function. Please also try squashing one commit as a fixup to reduce the complexity a bit.

This is really good work!

2024-02-10 09:27 UTC, milroy commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +	spec := C.CString(jobspec)
I think it needs to be freed here, but am curious what Tom thinks. 

This raises an interesting issue: I think we should try running Valgrind checks against the CGo code. There's evidence that it works: https://github.com/golang/go/issues/60600. That would be good to have in CI testing, but I think is beyond the scope of this PR.

2024-02-10 09:27 UTC, milroy commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
I left a comment on an earlier commit, but I'm not sure we need `MATCH_UNKNOWN`. If we leave it in, we need a check for this before incrementing the job counter. See my earlier comment.

2024-02-10 09:27 UTC, milroy commented on resource/reapi/bindings/c++/reapi_module.hpp
> +    static int match_allocate_multi (void *h, match_op_t match_op,
It's really helpful for reducing the number of RPCs to Fluxion.

2024-02-10 09:27 UTC, milroy commented on resource/reapi/bindings/c++/reapi_module_impl.hpp
> +    match_op_t match_op = (orelse_reserve)? match_op_t::MATCH_ALLOCATE_ORELSE_RESERVE
I believe this is to support `rq2`.

2024-02-10 09:27 UTC, milroy commented on resource/reapi/bindings/c/reapi_cli.h
> + *                   MATCH_ALLOCATE_ORELSE_RESERVE : Try to allocate and reseve
Nit: typo "reseve".

2024-02-10 09:27 UTC, milroy commented on resource/reapi/bindings/c/reapi_module.h
> + *                   MATCH_ALLOCATE_ORELSE_RESERVE : Try to allocate and reseve
Nit: typo.

2024-02-10 09:27 UTC, milroy commented on resource/policies/base/match_op.h
>  #ifndef MATCH_OP_H
It would be cleaner to rebase and squash this commit into 04c7a3510fac6b9ad4ae790a6a7f9ad6e67950e3 as a fixup (to drop this commit message). I don't think that will cause conflicts, but if it does you can leave this commit as is.

2024-02-12 23:55 UTC, zekemorton commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
The go bindings need to have a default value, though we weren't entirely sure what that value should be. I think MATCH_ALLOCATE would end up being the default option if we just removed MATCH_UNKNOWN

2024-02-13 00:28 UTC, trws commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
Why do we need a default?

2024-02-13 00:55 UTC, zekemorton commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
I think it's because the way we define the `MatchType` in go using `iota` means that an initialized but unset MatchType variable will use the 0 value or what we are calling a default. We can set that value to be one of the actual match options or some other value, in this case `MATCH_UNKNOW`. Is that about right @vsoch ?

2024-02-13 00:59 UTC, vsoch commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
Yes that's correct! We want to be able to distinguish between "this variable was not set" (0) vs. "this variable was set as match allocate" (1). If we had MatchAllocate as the first, then you couldn't tell between those two cases.

2024-02-13 01:20 UTC, trws commented on resource/reapi/bindings/go/src/fluxcli/reapi_cli.go
> +	spec := C.CString(jobspec)
Yup, spec needs to be freed.  Should be the usual `defer C.free(unsafe.Pointer(str))` or similar, at least unless things have changed.  The exception to this is cases where an API takes ownership of it and promises to free it later. The `var r` bit seems a bit off to me though.  Since that string is never used, a `var r *C.char = nil` might make more sense, no reason to pay to allocate it and free it if it's unused.  Whether the string placed there by reapi_cli_match needs to be freed I'd have to dig in to check but probably.

2024-02-13 01:26 UTC, trws commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
Hm, I suppose I can see where you're coming from. It's a downside to using an int for this rather than a true algebraic data type sadly. I guess this is ok, just wish we could make an unknown state unrepresentable.

2024-02-13 02:01 UTC, vsoch commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
If you always instantiate like:

```go
popcornState := Buttered
```
You are probably OK. The issue comes with if/for loops or similar where you need to define the variable at the top of the statement (unset) or similar, and then it may not always be clear if it was set to an explicit value (MatchAllocate == 0) or there is a bug and you forgot to set it.

2024-02-13 02:31 UTC, trws commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
Right, it makes sense, and FWIW  I have pushed for similar things in APIs where there needs to be an initial but still invalid value.  Suppose I'm just wishing for the rust or OCaml or haskell-style algebraic types where the language doesn't allow for a default-initialized instance, so you can't write `let mut a: PopcornFlavor;` and get away with it.  You can write it, but the compiler will inform you of your misdeeds rather rapidly:

```rust
 #[derive(Debug)]
 enum PopcornFlavor {
    Buttered,
    Salted,
    Kettle
 }
 pub fn main() {
    let mut a: PopcornFlavor;
    println!("{:?}", a)
 }
```

Result:
```shell
$ rustc /home/scogland1/test.rs
error[E0381]: used binding `a` isn't initialized
 --> /home/scogland1/test.rs:9:22
  |
8 |     let mut a: PopcornFlavor;
  |         ----- binding declared here but left uninitialized
9 |     println!("{:?}", a)
  |                      ^ `a` used here but it isn't initialized
  |
  = note: this error originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run w
ith -Z macro-backtrace for more info)
help: consider assigning a value
  |
8 |     let mut a: PopcornFlavor = todo!();
  |                              +++++++++

error: aborting due to previous error

For more information about this error, try `rustc --explain E0381`.
```

Ah well, better to have it so we can catch it when we can't prevent it otherwise.

2024-02-13 02:36 UTC, vsoch commented on resource/policies/base/match_op.h
> +enum class match_op_t { MATCH_UNKNOWN,
Ah if only the compiler would tell me about my misdeeds!! That's neat with rust, I wonder why Go didn't do similar.

2024-02-13 22:14 UTC, zekemorton commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +    if (match_op != match_op_t::MATCH_SATISFIABILITY)
Instead of doing this check before job increment, I added a check for a valid match option near the top of the function. Otherwise, it looks like a an invalid match option like `MATCH_UNKNOWN` would end up triggering logic for `MATCH_ALLOCATE`.

2024-02-14 07:49 UTC, milroy approved these changes
Great work iterating on this and integrating everyone's suggestions @zekemorton! This has been an epic PR conversation.

2024-02-14 07:49 UTC, milroy commented on resource/reapi/bindings/c++/reapi_cli_impl.hpp
> +    if (match_op != match_op_t::MATCH_SATISFIABILITY)
I can't find that check in `reapi_cli_t::match_allocate `, but maybe it's in a different commit. Can you point it out to me?

2024-02-14 17:11 UTC, zekemorton commented
Looks like I accidentally squashed the commit it was a part of, so I just un-squashed it! Should now be in https://github.com/flux-framework/flux-sched/pull/1133/commits/e7e78f82986feb4e5e12d67f340a83e540d27258

2024-02-15 01:26 UTC, milroy reviewed
Some `enum` type specifiers crept into function signatures and should be removed. It is correct to include the type specifier as well (see https://en.cppreference.com/w/cpp/language/elaborated_type_specifier), but it is inconsistent with the majority of Fluxion code. 

Once that's fixed this should be ready to merge.

2024-02-15 01:26 UTC, milroy commented on resource/policies/base/match_op.h
> +static const char *match_op_to_string (enum match_op_t match_op) {
No need to specify `enum` type here:
```suggestion
static const char *match_op_to_string (match_op_t match_op) {
```

2024-02-15 01:26 UTC, milroy commented on resource/policies/base/match_op.h
> +static bool match_op_valid (enum match_op_t match_op) {
No need to specify `enum` type here:
```suggestion
static bool match_op_valid (match_op_t match_op) {
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c++/reapi.hpp
> +     *  \param match_op  enum match_op_t: set to specify the specific match option
```suggestion
     *  \param match_op match_op_t: set to specify the specific match option
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c++/reapi.hpp
> +     *  \param match_op  enum match_op_t: set to specify the specific match option
```suggestion
     *  \param match_op match_op_t: set to specify the specific match option

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c/reapi_cli.cpp
> +                                enum match_op_t match_op, const char *jobspec,
No need for `enum` type in function signature.
```suggestion
                               match_op_t match_op, const char *jobspec,
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c/reapi_cli.h
> +int reapi_cli_match (reapi_cli_ctx_t *ctx, enum match_op_t match_op,
No need for `enum` type in function signature.
```suggestion
int reapi_cli_match (reapi_cli_ctx_t *ctx, match_op_t match_op,
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c/reapi_module.cpp
> +                                   enum match_op_t match_op, const char *jobspec,
No need for `enum` type in function signature.
```suggestion
                                 match_op_t match_op, const char *jobspec,
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c/reapi_module.h
> +int reapi_module_match (reapi_module_ctx_t *ctx, enum match_op_t match_op,
No need for `enum` type in function signature.
```suggestion
int reapi_module_match (reapi_module_ctx_t *ctx, match_op_t match_op,
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c/reapi_module.h
> + *  \param match_op  enum match_op_t: set to specify the specific match option
```suggestion
 *  \param match_op match_op_t: set to specify the specific match option
```

2024-02-15 01:26 UTC, milroy commented on resource/reapi/bindings/c/reapi_cli.h
> + *  \param match_op  enum match_op_t: set to specify the specific match option
```suggestion
 *  \param match_op match_op_t: set to specify the specific match option
```

2024-02-15 01:54 UTC, trws commented on resource/policies/base/match_op.h
> +static const char *match_op_to_string (enum match_op_t match_op) {
Is this a C++-only header? I thought this was C, where it's required unless there's a `typedef` to alias the enum to the unqualified name.

2024-02-15 01:56 UTC, trws commented on resource/policies/base/match_op.h
> +static const char *match_op_to_string (enum match_op_t match_op) {
We do usually do that though... Oh I see, it used to be in a C++ file and was moved here.  The equivalent would be to make it:

```c
typedef enum match_op_t { MATCH_UNKNOWN,
                  MATCH_ALLOCATE,
                  MATCH_ALLOCATE_W_SATISFIABILITY,
                  MATCH_ALLOCATE_ORELSE_RESERVE,
                  MATCH_SATISFIABILITY } match_op_t;
```

That way it can be used bare, which is what we do most places.

2024-02-15 16:50 UTC, zekemorton commented on resource/policies/base/match_op.h
> +static const char *match_op_to_string (enum match_op_t match_op) {
This is super helpful, thanks so much for the suggestion! This is definitely cleaner and more constant with the rest of the code, I just wasn't sure that I could/how to do it before. Went ahead and made those changes, so should be ready now!

2024-02-16 02:56 UTC, milroy commented on resource/policies/base/match_op.h
> +static const char *match_op_to_string (enum match_op_t match_op) {
Yeah, that's a clean solution!

2024-02-16 03:01 UTC, milroy approved these changes
LGTM. Thanks for all the hard work pushing this through!

2024-02-16 17:08 UTC, merged

2024-02-16 17:09 UTC, vsoch commented
yes!! :partying_face: