[WIP] Add support for broker rank-based partial release
flux-framework/flux-sched pull request #1163
Opened 2024-04-08 08:22 UTC by milroy

Fluxion issue #1151 and [flux-core issue 4312](https://github.com/flux-framework/flux-core/issues/4312) describe the need for partially releasing broker resources. The first implementation of the functionality is scoped to releasing all resources managed by a single broker rank per RPC. Elasticity considerations will require arbitrary release of resources, but this capability may only be needed in the scheduler.

In its current WIP state, this PR adds capability to identify all `boost` graph vertices managed by a broker rank in the _RV1_ reader. The reader builds and returns a map keyed by the resource types, with values corresponding to the number of resources of that type to be removed. The cancellation of the vertices occurs in the _RV1_ reader, and the partial cancellation an pruning filter updates occurs in the traverser. Note that the map is under-specified relative to number of resources in the resource graph. The traverser uses vectors of types and counts that are ordered by their visit order. Since the reader may unpack and find the boost vertices in any order (and lookups need to be fast) a map is the better choice for container. The complexity of translating between map and vector containers was added to the planners in PR #1061.

The `planner` and `planner_multi` need modifications to handle span reduction based on the assembled reduction counts and types. They must deal with `0` entries for reduction, correctly treat a sequence of span reductions as a single span removal. A single partial cancellation that contains all `planner` or `planner_multi` resources must behave like a full span removal. The planners must also return whether the span was totally removed to the client.

The traverser begins a depth-first visit that stops as soon as it encounters a vertex untagged and cancelled by the _RV1_ reader. The traverser needs a new `enum class` to designate job modification traversal types. If the type is `PARTIAL_CANCEL`, the traverser must only untag and erase the `jobid` if the planner indicates that the removal constitutes a full removal.

Items remaining to be completed to remove the WIP tag:

- [ ] Add RPC handling
- [ ] Add REAPI support
- [ ] Add tests in testsuite

2024-06-27 06:23 UTC, milroy commented
@zekemorton, @trws, @jameshcorbett: please take a look at the current state when you get a chance. Getting your feedback soon will help me make sure this PR is on the right track.

2024-06-28 19:31 UTC, grondo commented
@milroy - Is this branch ready for any testing? I've got @garlick's houskeeping PR (flux-framework/flux-core#5818) installed on a test cluster, but with sched-simple for now since it supports partial release. If it would be helpful I could start testing with this branch instead. Our hope it to include housekeeping as an experimental feature in the next release, currently scheduled for July 2.

2024-07-01 22:20 UTC, jameshcorbett reviewed
I did a quick pass-through. There are a lot of changes but I think they make sense and look good! I will do another more careful pass later. The inline comments are very helpful but commit message bodies would often help a lot with figuring out what's going on.

2024-07-02 04:59 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +   return -1;
> Because core will never send a partial cancel RPC in the form of JGF as I understand it?

I don't think there are plans to send a `free` RPC with JGF payload from core. It will be useful in cloud environments.

2024-07-02 04:59 UTC, milroy commented on resource/traversers/dfu_impl_update.cpp
> +    job2span.erase (jobid);
I'll definitely do that once I get this out of WIP state.

2024-07-02 05:02 UTC, milroy commented on resource/planner/c/planner_c_interface.cpp
> +    if (to_remove == span->planned) {
Yes, this works whenever you're releasing some resource types but not others (which will be released in a future `free` RPC).

2024-07-02 05:05 UTC, milroy commented
Thanks for the initial feedback @jameshcorbett !

2024-07-02 05:11 UTC, milroy commented
The remaining problem with this PR is related to the new requirement for `queue_policy_base_t` objects to call REAPI. See here: https://github.com/flux-framework/flux-sched/blob/37457071cd3dbcb7116661b2837b56027d99abaa/qmanager/policies/queue_policy_bf_base_impl.hpp#L170.

So far, sched-resource calls can only be made via templated, derived classes like `bf_base` and `fcfs`. I supposed I could rework `queue_policy_base_t`, to be templated on `reapi_type`, but that will probably be a big change. @trws or @jameshcorbett, do you have suggestions here?

2024-07-02 19:03 UTC, trws commented on resource/reapi/bindings/c++/reapi_module_impl.hpp
> +                                          "full-removal", &ret_removal)) < 0) {
Stack smashing from here.  Valgrind test reported it at end of function, and these variadic monstrosities are always good candidates. In this case, the `b` specifier expects an _int_ sized value, rather than a C++-style 1-byte bool. Change ret_removal to an int to get past that one.  There may be others.

2024-07-03 09:04 UTC, milroy commented on resource/reapi/bindings/c++/reapi_module_impl.hpp
> +                                          "full-removal", &ret_removal)) < 0) {
Thanks for catching this!

2024-07-04 02:19 UTC, milroy commented
The test failure in `t1009-recovery-multiqueue.t` occurs here: https://github.com/flux-framework/flux-sched/blob/1161e61a1ca56d6a4cbad6e137e41bbe968e5444/t/t1009-recovery-multiqueue.t#L81

It hangs almost all the time, but I've seen it succeed once. I did check to make sure the cancellation on the previous line is working as expected.

2024-07-04 02:26 UTC, milroy commented
The other test that fails is `t1013-qmanager-priority.t`, and the failing subtest is here: https://github.com/flux-framework/flux-sched/blob/1161e61a1ca56d6a4cbad6e137e41bbe968e5444/t/t1013-qmanager-priority.t#L135

2024-07-04 03:21 UTC, trws commented
These two tests are the ones I've seen break most often lately. Almost anything that changes the qmanager sched loop ordering or pending handling can break those.  I'll take a look and see if I see any of the "usual suspects" that kept biting me in the other PRs.

2024-07-04 03:45 UTC, trws commented
Nothing is jumping out at me as likely in the new remove methods, but I think you can simplify those pretty significantly. Specifically, I'd say consider doing the "cancel" in the new method, then invoking the _old_ remove method if it's a full cancel.  It may need some conditions there to make sure it only does the cancel in the right case and so-forth, but that should cut down the duplication and keep you from having to re-implement the cancellation logic in the new ones.

2024-07-04 03:45 UTC, trws commented
Sorry, I meant the "in-progress sched loop cancellation logic" rather than the partial cancellation logic. Words hard 😐

2024-07-06 01:49 UTC, milroy commented
> Specifically, I'd say consider doing the "cancel" in the new method, then invoking the old remove method if it's a full cancel. 

The way partial cancel is currently implemented is it is the same as a full cancel if it cancels all the job's resources (or all the job's remaining resources if it's the final RPC in a sequence of partial cancels). So it's redundant to invoke a full cancel afterward.

2024-07-06 01:51 UTC, milroy commented
I found a way to get the tests to pass but I'm not too happy with it. If the sched loop is invoked after partial cancel in the derived-class `remove` everything works as expected...

2024-07-06 01:52 UTC, milroy commented
@grondo this PR is ready for the test cluster whenever you get a chance.

I'm going to update the commit messages soon and will drop the WIP label.

2024-07-06 02:36 UTC, garlick commented
Nice!  I'll put it on mine tomorrow.

2024-07-06 03:38 UTC, milroy commented
> I found a way to get the tests to pass but I'm not too happy with it. If the sched loop is invoked after partial cancel in the derived-class remove everything works as expected...

With the changes in this PR the 10,000 job submit and cancel test with blocked jobs now runs in 31 seconds (versus 47s with `master`) in the bookworm container on my laptop. @trws you may want to run a test as well.

2024-07-06 08:46 UTC, milroy commented
This PR is ready for review, and I'll tag folks after the weekend.

2024-07-06 15:42 UTC, garlick commented
On my test cluster (`v0.36.0-26-g34b5f692`) right now and things are looking great so far for simple runs.  I have to run an errand and then I"ll try some more stuff.  Any particular things I should try to probe?

2024-07-06 19:08 UTC, trws commented
> > Specifically, I'd say consider doing the "cancel" in the new method, then invoking the old remove method if it's a full cancel.
> 
> The way partial cancel is currently implemented is it is the same as a full cancel if it cancels all the job's resources (or all the job's remaining resources if it's the final RPC in a sequence of partial cancels). So it's redundant to invoke a full cancel afterward.

That makes sense, the idea though is to avoid the logic triplication for removals. As an alternative, could each of the derived classes provide a function just implementing the difference, which looks like this part:

```c++
if ( (rc = reapi_type::cancel (h, job_it->second->id, R, true,
                                       full_removal) != 0))
            break;
```

So that way we can have two entry points to remove implemented in the queue_policy_base class, the partial cancel one that takes a handle and R, and the id-only one that would delegate to the partial cancel one.  The partial cancel remove could then call a virtual method for just the cancel call if it has been provided with R and a handle, and we only need one copy of the state logic, loop and blocked job handling logic.

Anyway, I'll do a deeper look here, but keeping the control flow for qmanager sane is really, really tricky because of the way it's laid out right now.  If possible it would be good to minimize the number of alternate code paths we need to worry about that deal with the state machine.

2024-07-06 19:49 UTC, milroy commented
> Any particular things I should try to probe?

Yes, please check that a sequence of partial releases is equivalent to a full cancel. So submit a job of N nodes and issue N partial releases. Then try to schedule the exact same nodes. Another good test is to release ranks with different resources like cores and GPUs (if you have or can simulate them). Finally, please test partial release of non exclusive jobs, especially with cores in GPUs, if possible.

2024-07-06 19:56 UTC, milroy commented
> That makes sense, the idea though is to avoid the logic triplication for removals. As an alternative, could each of the derived classes provide a function just implementing the difference

> So that way we can have two entry points to remove implemented in the queue_policy_base class, the partial cancel one that takes a handle and R, and the id-only one that would delegate to the partial cancel one. 

Ah, I see what you mean. I'll get to work on it!

>  If possible it would be good to minimize the number of alternate code paths we need to worry about that deal with the state machine.

Yeah, we don't want to make it any more complicated than absolutely necessary.

2024-07-07 00:27 UTC, trws commented on resource/modules/resource_match.cpp
> +    std::map<uint64_t, uint64_t>::iterator jobid_it;
If we can't use auto for things like iterators because of placement and gotos for now, perhaps we can at least use decltype on the variable so if we decide to change the specific type later it's less painful.

```suggestion
    decltype(ctx->allocations)::iterator jobid_it;
```

2024-07-07 22:19 UTC, milroy commented on resource/modules/resource_match.cpp
> +    // RV1exec only reader supported currently
It's the only reader supported with resource match in production currently. Production uses will just use `Rlite` to grab the ranks for any `.free` RPC. Cloud use cases can use JGF, but that won't be using resource match currently, and is "experimental."

I do add JGF support in a later commit, but there aren't any plans to use it in production.

2024-07-07 22:21 UTC, milroy commented on resource/modules/resource_match.cpp
> +    std::map<uint64_t, uint64_t>::iterator jobid_it;
That's slick; thanks! Implemented.

2024-07-07 22:24 UTC, milroy commented on resource/modules/resource_match.cpp
> +    full_removal? (int_full_removal = 1) : (int_full_removal = 0);
I don't know why I did that... Changed to the simpler version you suggested.

2024-07-07 22:24 UTC, milroy commented on resource/modules/resource_match.cpp
> +                                       "full-removal", (int)full_removal) < 0)
It was vestigial; thanks for catching it.

2024-07-07 22:41 UTC, milroy commented on resource/planner/c++/planner_multi.cpp
> +    //std::string rtype = std::string (type);
Actually, this wasn't a change I added in this PR, it was from an earlier PR. The comment above about the later commit that fixes these string constructions holds.

2024-07-08 19:51 UTC, trws commented on qmanager/policies/queue_policy_bf_base_impl.hpp
> +}
Wow, this came out great. I love to see the "cancel_completed_jobs" stuff go too.  Is that all because things are getting explicitly rather than implicitly cancelled through the `m_completed` queue?

2024-07-08 23:42 UTC, milroy commented on qmanager/policies/queue_policy_bf_base_impl.hpp
> +}
Yes, that's precisely why. It was a good suggestion!

2024-07-09 00:00 UTC, trws requested changes
I'm happy with how much of this is turning out.  The run_sched_loop in remove is concerning me though.  After some testing locally, it looks like the only test that fails with the `run_sched_loop` removed is t1009-recovery-multiqueue, and that one works if it waits for `jobid3` rather than `jobid4` as it currently does (it expects job4 to start, even though job3 has higher priority).  It strikes me as really odd that this is the PR that makes this show up, but at least that way the requirements around the order of sched loop cleanup and starting the next one stay as they were.

I think what's going on is that until just recently we always did the queue management in a very specific order, and as a result cancelling job2 always freed job4 because they were in the same queue, and there is no way that the other queue would get considered before the queue they're on.  Now it seems that it's much more likely that the other queue is considered first for some reason.  It's probably a combination of eagerly canceling the job, rather than deferring it to the beginning of the next sched loop, and the recent async queues work.

Anyway, as I read it, take the `run_sched_loop` out of the `remove` method, and make `t1009` accept _either_ job3 or job4 starting within the timeout. Just one of them has to, don't care which.

2024-07-09 00:27 UTC, milroy commented on resource/planner/test/planner_test01.cpp
> +    test_partial_cancel ();
Thanks for finding this.

2024-07-09 00:35 UTC, milroy commented
> The run_sched_loop in remove is concerning me though. After some testing locally, it looks like the only test that fails with the run_sched_loop removed is t1009-recovery-multiqueue

Yes, that's the reason I added `run_sched_loop`. It didn't seem like the right thing to do, but it was the only thing I tried that allowed `t1009-recovery-multiqueue.t` to pass without modifying the test.

> Anyway, as I read it, take the run_sched_loop out of the remove method, and make t1009 accept either job3 or job4 starting within the timeout. Just one of them has to, don't care which.

It looks like job3 starts before job4 every time now. Is there a way to use a boolean operator with `wait-event`, or is it fine to just do `flux job wait-event -t 10 ${jobid3} start || flux job wait-event -t 10 ${jobid4} start`?

2024-07-09 00:57 UTC, trws commented
Yeah, I'm seeing it start job3 every time as well, but knowing that code I'm not at all certain that's guaranteed. The first thought that comes to mind is make them wait able and use wait to wait for the first of the two (since it grabs whichever finishes first) but then they would have to be switched to short runtimes. I'm not sure if wait-event has a similar option, worth looking (I'm on a phone right now and couldn't find it quickly).

2024-07-09 01:38 UTC, grondo commented
No option in wait-event to wait on multiple jobs (a good idea though), but it would be trivial to write a python script to do it.

2024-07-09 01:49 UTC, milroy commented
> No option in wait-event to wait on multiple jobs (a good idea though), but it would be trivial to write a python script to do it.

It's not important for this PR. I can just use `||` between the two commands. The worst case scenario is the test takes 20s to fail instead of 10. I favor two-command approach over shortening the test job runtimes because that might introduce races with the cancellations given the previous `wait-events` on start and submit events.

2024-07-09 06:03 UTC, milroy commented
> Anyway, as I read it, take the run_sched_loop out of the remove method, and make t1009 accept either job3 or job4 starting within the timeout. Just one of them has to, don't care which.

@trws: I've addressed your concern in `qmanager`, but let me know if you want me to treat `t1009` differently.

2024-07-09 13:16 UTC, trws commented
Works for me, if it ever comes up as a perf concern we can deal with it then. Great job @milroy, love the cleanup you did along the way.

2024-07-09 13:17 UTC, trws approved these changes

2024-07-09 14:39 UTC, grondo commented
Since this was also asked in slack, here's a small script to wait for the `start` event for any number of jobs and exit with success on the first:

```python
import sys
import flux
from flux.job import JobID, event_watch_async

found = False
handle = flux.Flux()

def event_cb(future, jobid):
    event = future.get_event()
    print(f"{jobid.f58}: {event}")
    if event.name == "start":
        found = True
        handle.reactor_stop()

for jobid in sys.argv[1:]:
    jobid = JobID(jobid)
    event_watch_async(handle, jobid).then(event_cb, jobid)

handle.reactor_run()
if not found:
    print("start event for job never appeared", file=sys.stderr)
    sys.exit(1)

```

2024-07-09 16:44 UTC, trws commented
Oh cool, thanks @grondo!

2024-07-09 19:27 UTC, trws commented
@milroy, ready for MWP?

2024-07-09 19:58 UTC, grondo commented
@trws, @milroy, @jameshcorbett, what do you think about tagging another flux-sched release once this goes in? Then we can get a working housekeeping setup on fluke for testing asap..

2024-07-09 22:08 UTC, trws commented
I'd be happy to see that happen.  Just need @milroy's sign-off to push this in.

2024-07-09 23:10 UTC, milroy commented
I'm going to amend one commit to add REAPI CLI support for partial cancel as well. It should be ready within the hour.

2024-07-10 00:43 UTC, milroy commented
Thanks for the feedback and testing @trws, @garlick, and @grondo!

Setting MWP.

2024-07-10 00:45 UTC, merged