Support and handle optional "final" flag in .free RPC
flux-framework/flux-sched pull request #1266
Opened 2024-08-10 02:26 UTC by milroy

Recently, a large job on a large system was considered allocated by Fluxion, but was complete and released in flux-core (https://github.com/flux-framework/flux-core/issues/6179). The proposed solution was to amend RFC 27 to include an optional "final" boolean flag in the `.free` RPC. That flag can be used by Fluxion to determine if there is an allocation state discrepancy between flux-core and sched.

This PR adds support to handle the optional "final" flag in the `.free` RPC. The current implementation only logs an error when a state discrepancy is detected, but doing a full cancellation of the job would be a straightforward addition to this PR.

2024-08-10 22:08 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux.Flux().rpc('sched.free', obj)
Note that adding a `.get()` to this line causes the script to hang indefinitely. The action occurs as expected without `.get()`. I'm a bit concerned about the behavior but haven't figured out how to fix it.

Note that there's no real error checking in this test. I think the best way to check for errors would be to parse the  RPC output...

2024-08-10 22:11 UTC, milroy commented
@trws, this PR is ready for review. There are still two issues I'm trying to fix:

1. See the note about `.get()` hanging for the `.free` RPC in the testsuite test
2. `clang-format` is changing one or more files in this PR, and I can't reproduce it in the container in my dev environment

2024-08-10 22:25 UTC, milroy commented
@garlick or @grondo, it may be good for one of you to take a look at this, too.

2024-08-11 14:02 UTC, grondo commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux.Flux().rpc('sched.free', obj)
The `sched.free` RPC doesn't have a response (see the documentation of the [sched.free](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_27.html#free) request in RFC 27).

2024-08-11 14:29 UTC, grondo reviewed
Just adding a few suggestions to the test, since I 'm not qualified to fully review the other parts of the PR.

2024-08-11 14:29 UTC, grondo commented on t/issues/t6179-flux-core-housekeeping.sh
> +jobid = int(sp.check_output(['flux', 'job', 'id', sys.argv[1]]).decode())
Instead of using a subprocess to run `flux job id`, just use the Python `JobID` class:

```python
from flux.job import JobID

jobid = JobID(sys.argv[1])
```

2024-08-11 14:29 UTC, grondo commented on t/issues/t6179-flux-core-housekeeping.sh
> +path = "R"
Instead of using a manually created _R_, it might be easier to define `resource.config` in the config file, e.g.
```toml
[[resource.config]]
hosts = "node[0-1]"
cores = "0-15"
gpus = "0-3"
```

Only a suggestion or illustrative for next time since _R_ works fine here too.

2024-08-11 14:29 UTC, grondo commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux python ./free.py ${jobid1}
There may be a small race condition that could cause this sequence to fail if the job submitted above doesn't get an `alloc` event before `free.py` is run. In that case the scheduler hasn't yet seen the job so `free.py` would be failing (though as you note, this currently isn't checked)

Add `--wait-event=alloc` to `flux submit` to ensure the scheduler has allocated resources before  proceeding with the test.

2024-08-11 14:29 UTC, grondo commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux python ./free.py ${jobid1}
This probably goes for the other jobs submitted in the test as well.

2024-08-11 14:29 UTC, grondo commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux job wait-event -t 5 ${jobid1} release
Between the free and the cancel is there some way to check that the job (eventually) reaches a consistent state? That is, could you send a query to Fluxion (perhaps `sched-fluxion-resource.resource-status`) to ensure all resources have been released with the `final=true` flag? (There might have to be a retry since `free.py` won't block until a response...)

2024-08-12 00:42 UTC, trws requested changes
There are a couple bits to think about in the control flow, but this is a great improvement.  I think the `.get()` issue is just the lack of response as @grondo mentioned, so that should be fine.

2024-08-12 00:42 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +        flux_h = static_cast<flux_t *> (h);
```suggestion
        flux_t *flux_h = static_cast<flux_t *> (h);
```

2024-08-12 00:42 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
This logic looks really good, I like the flow.  One concern I have though is that the two new `goto out` lines skip the `cancel_sched_loop ();` and `reconsider_blocked_jobs ()` lines where originally the failure path used `break` to drop out of the switch and kept those.

2024-08-12 00:42 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    errno = EPROTO;
Is this a protocol error? What causes a cancel failure at this point, invalid R?  The other one definitely seems like EPROTO but I would have guessed EINVAL here.

2024-08-12 00:42 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                        goto out;
I may be misreading the logic, but it seems like if the second cancel succeeds,
it should be logged but probably shouldn't return error? Feel free to push back
on this one since I'm not sure what effects are at the callsite outside this but
if the resources are freed that seems substantially less broken than if some of
them couldn't be removed.

```suggestion
                        flux_log_error (flux_h,
                                        "%s: Final .free RPC failed to remove all resources for "
                                        "jobid "
                                        "%jd",
                                        __FUNCTION__,
                                        static_cast<intmax_t> (id));

                        if (cancel (h, job_it->second->id, true) != 0) {
                            errno = EPROTO;
                            goto out;
                        }
```

2024-08-12 00:42 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
>                  set_schedulability (true);
I think this line now needs to move up, maybe even to the start of this case? We should run the sched loop after any clearing of resources, even if something went slightly wrong, otherwise we might block for lack of incoming events.

2024-08-12 02:50 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +jobid = int(sp.check_output(['flux', 'job', 'id', sys.argv[1]]).decode())
Good suggestion! Implemented.

2024-08-12 02:51 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +path = "R"
Also good idea! I'm not sure why I wrote it the other way originally...

2024-08-12 02:51 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux python ./free.py ${jobid1}
> Add --wait-event=alloc to flux submit to ensure the scheduler has allocated resources before proceeding with the test.

Thanks for the suggestion! Implemented.

2024-08-12 02:52 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux job wait-event -t 5 ${jobid1} release
Good idea. I can do that with `flux ion-resource find "sched-now=allocated"`.

2024-08-12 02:53 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +        flux_h = static_cast<flux_t *> (h);
Oof, thanks for catching that.

2024-08-12 03:03 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
I was going back and forth on this in part due to the use of `goto` if the job `id` isn't found in `m_jobs`: https://github.com/flux-framework/flux-sched/blob/6d2dc56d316c443216dc96ab6c03b46df33bc602/qmanager/policies/base/queue_policy_base.hpp#L517

But I suppose this error shouldn't prevent `cancel_sched_loop ()` and `reconsider_blocked_jobs ()` from getting called.

2024-08-12 03:07 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    errno = EPROTO;
Yes, that's one possibility. A general traverser error can cause it, too. I'm actually not sure if we want to log this error here since it gets logged in the `qmanager_free_cb` and in `resource_match`. As in the code above I think the return code shouldn't be `0` if `cancel` experiences an error.

2024-08-12 03:08 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
However, I think the return code shouldn't be `0` if `cancel` experiences an error, so I'll need to adjust this commit a bit to use a `break` and return `-1`.

2024-08-12 04:05 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
>                  set_schedulability (true);
How about moving `set_schedulability (true);` right before the return?

2024-08-12 04:07 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                        goto out;
> I may be misreading the logic, but it seems like if the second cancel succeeds,
it should be logged but probably shouldn't return error? 

I didn't write this in a very clear fashion. There are actually two error conditions here, and the current implementation only logs one. I've updated the code to log both.

2024-08-12 04:08 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    errno = EPROTO;
After more thought, I think logging an error if `cancel` fails provides useful information.

2024-08-12 04:17 UTC, milroy commented
> Take a look at https://github.com/flux-framework/flux-sched/pull/1267 and maybe rebase on there, I didn't realize we wouldn't get the format change on failure, and we definitely should so that adds it.

Yeah, that PR identified the formatting issue. Thanks!

2024-08-12 04:20 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux job wait-event -t 5 ${jobid1} release
I'm not sure of the best way to perform a retry, though.

2024-08-12 19:24 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
That sounds like a good plan.  The main difference with the m_jobs check is that if there's no job, we don't actually do any canceling, there's no effect to cause the sched loop to need to update something.  If there's an error from cancel that means the same thing "no removal took place" then we should probably do the same, but if the set of free resources changed then the `set_schedulable` and the other two need to run.

2024-08-12 19:24 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    errno = EPROTO;
Ok, that seems reasonable, thanks @milroy.

2024-08-12 19:25 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
>                  set_schedulability (true);
That would work too, as long as we're doing it in every case where something actually changes.  If we can avoid calling it when nothing changes, that keeps resource usage down, but setting it too often should still execute correctly.

2024-08-13 03:41 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
> If there's an error from cancel that means the same thing "no removal took place" then we should probably do the same, but if the set of free resources changed then the set_schedulable and the other two need to run.

Unfortunately, I don't think `cancel` is atomic.

2024-08-13 03:42 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
>                  set_schedulability (true);
The guideline of setting schedulability only if the resource state changes does suggest moving`set_schedulability (true);` is the best approach with the understanding that `cancel` isn't atomic.

2024-08-13 03:44 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux.Flux().rpc('sched.free', obj)
I missed that the RPC doesn't have a response.

2024-08-13 03:49 UTC, milroy commented on t/issues/t6179-flux-core-housekeeping.sh
> +flux job wait-event -t 5 ${jobid1} release
I decided to just rerun the check.

2024-08-13 03:50 UTC, milroy commented
@trws and @grondo this PR is ready for another look.

2024-08-13 16:30 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
What do you mean by atomic in this context?

2024-08-13 16:44 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
There are failure modes where it partially removes an allocation (in the case of full cancellation) or part of the set of resources designated to be deallocated (in the case of partial cancel). So if `cancel` fails the resource graph isn't necessarily in the same state it was in before the `cancel`.

2024-08-13 17:02 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    goto out;
Gotcha, makes sense.

2024-08-13 17:05 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    set_schedulability (true);
I think this now runs only on a full removal or a final release right? Maybe it should go just above the enclosing if statement to catch non-final partial releases as well?

2024-08-13 17:06 UTC, trws approved these changes
Ok, I'm happy with this pending the move of the set_schedulability call so we still start a loop on a successful partial release.  Good stuff @milroy!

2024-08-13 17:51 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    set_schedulability (true);
You're right. I moved the statement right before the enclosing `if`.

2024-08-13 17:55 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    set_schedulability (true);
Unfortunately, `t1001-qmanager-basic.t` fails with that change. Investigating...

2024-08-13 17:57 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    set_schedulability (true);
It's the new check for qmanager stats:
```bash
expecting success: 
    flux module stats sched-fluxion-qmanager | tee stats.json &&
    jq -e ".queues.default.action_counts.rejected == 1" stats.json &&
    jq -e ".queues.default.action_counts.complete >= 4" stats.json

{
 "tx": {
  "request": 27,
  "response": 5,
  "event": 0,
  "control": 0
 },
 "rx": {
  "request": 10,
  "response": 22,
  "event": 0,
  "control": 0
 }
}
false
not ok 9 - qmanager: check stats
```

2024-08-13 18:11 UTC, trws commented on qmanager/policies/base/queue_policy_base.hpp
> +                    set_schedulability (true);
It also looks like CI is passing, maybe a local rebuild issue?

2024-08-13 18:18 UTC, milroy commented on qmanager/policies/base/queue_policy_base.hpp
> +                    set_schedulability (true);
Yeah, it's a local build issue.

2024-08-13 18:19 UTC, milroy commented
Thanks for the feedback @trws and @grondo! Setting MWP.

2024-08-13 18:20 UTC, merged