Clear traverser before and after traversal operations in resource_match
flux-framework/flux-sched pull request #1323
Opened 2024-12-18 07:42 UTC by milroy

Recent debugging revealed that the traverser error message wasn't getting cleared after some traversal operations, leading to spurious or error logging that can be unrelated to the error cause.

Wrap each traverser function call with `clear_err_message ()` to ensure error messages are correctly attributed to the cause.

2025-01-05 18:29 UTC, jameshcorbett approved these changes
Looks reasonable and harmless. Did you verify this makes error messages more reasonable?

2025-01-08 17:58 UTC, milroy commented
> Did you verify this makes error messages more reasonable?

I'm looking at the test cases to see if there's a straightforward way to check that the message has been cleared.

2025-01-09 19:40 UTC, trws requested changes
I like what this is doing, but I'd prefer to have the `clear_err_message` calls at the beginning of the mark, run and find functions rather than their callers so we get that consistently between the module and command callers. If I'm reading it right, it should work to put them at the start of the methods in the dfu_traverser_t type in dfu.cpp.

2025-01-09 20:04 UTC, milroy commented
> If I'm reading it right, it should work to put them at the start of the methods in the dfu_traverser_t type in dfu.cpp.

That makes sense. I'll update the commit shortly.

2025-01-09 20:55 UTC, milroy commented
@trws, I updated the PR to address your change request and added an additional commit to remove the error message clearing from the resource match callers.

Let me know if the PR needs additional changes.

2025-01-09 22:24 UTC, milroy commented
I just remembered that the error message is actually member data of `dfu_impl_t` and `dfu_traverser_t` calls methods that change the error message.

I think we want to clear the error message at the beginning of methods in `dfu_impl_t`.

2025-01-09 22:26 UTC, trws approved these changes
Looks great, thanks @milroy!

2025-01-09 22:31 UTC, trws commented
> I just remembered that the error message is actually member data of `dfu_impl_t` and `dfu_traverser_t` calls methods that change the error message.
> 
> I think we want to clear the error message at the beginning of methods in `dfu_impl_t`.

I see what you mean, but I _think_ it's already where we want it.  The error message accumulates errors or issues as it passes through `dfu_impl_t` methods (hence all the `+= err` stuff).  With the clears in the `dfu_traverser_t` we should get the full error from whatever `dfu_impl_t` operations it ran as part of the traverser operation, where if we clear at the start of each of the `impl` methods we'd only get the last one unless we ensure that we propagate any error eagerly.

2025-01-09 23:50 UTC, milroy commented
> With the clears in the dfu_traverser_t we should get the full error from whatever dfu_impl_t operations it ran as part of the traverser operation, where if we clear at the start of each of the impl methods we'd only get the last one unless we ensure that we propagate any error eagerly.

That's a good point. I'll leave the clear calls in the `dfu_traverser_t` public API.

2025-01-10 00:42 UTC, milroy commented
The PR is good to go. I'm setting MWP. Thanks for the feedback @trws and @jameshcorbett!

2025-01-10 01:05 UTC, milroy commented
> I'm looking at the test cases to see if there's a straightforward way to check that the message has been cleared.

As an update, I can't think of an easy way to add a check for an uncleared error message.

2025-01-10 01:21 UTC, merged