[WIP] Add resource Id remapping support
flux-framework/flux-sched pull request #773
Opened 2020-11-24 07:31 UTC by dongahn

This PR is work in progress. 

* Add initial support to aid in remapping resource Id and rank efficiently for nested instances (i.e., `class resource_namespace_remapper_t`)
* Integrate it into the base resource reader class to make it available for all of the reader classes
* Fix incorrect GPU numbering of our hwloc reader using this support
* Modify `sched-fluxion-resource` to establish correct GPU remapping for hwloc reader. The hwloc reader of a nested flux instance discovers the GPU resources using hwloc. However, hwloc uses the logical Id space for each discovered GPU resource, which does not work with GPU affinity at execution time (i.e., `CUDA_VISIBLE_DEVICES`).

2020-11-28 23:25 UTC, dongahn commented
@Mergefyio rebase

2020-11-28 23:29 UTC, dongahn commented
@Mergifyio rebase

2020-11-28 23:31 UTC, dongahn commented
This is good for your review. 

While testing this on rzansel with actual GPUs, I found a couple of problems with flux-core. I posted a PR for one problem: https://github.com/flux-framework/flux-core/pull/3376

But I don't think we have any immediate solution for the other: https://github.com/flux-framework/flux-core/issues/3375

2020-12-01 19:36 UTC, milroy requested changes
This looks great @dongahn, but may need a few minor changes that I highlighted.

2020-12-01 19:36 UTC, milroy commented on t/scripts/flux-ion-resource.py
> +    def rpc_namespace_info (self, rank, type_name, Id):
Nit: IMHO `Id` is too close to `id`, which is a built-in Python function.  This isn't a necessary change.

2020-12-02 17:08 UTC, dongahn commented on resource/readers/resource_namespace_remapper.cpp
> +/*****************************************************************************\
Sorry about this. I will clean up the commit message. Thanks!

2020-12-02 17:18 UTC, dongahn commented on resource/readers/resource_namespace_remapper.cpp
> +                                                           uint64_t>> ();
As we discussed, I picked readability and simplicity over optimization for the initial condition. I think it makes sense to add this in this case so I will try to add this. But I have a slight reservation on the use of `goto` statement for success as a unconventional control flow can be confusing. So I will try to avoid it.

2020-12-02 17:18 UTC, dongahn commented on resource/modules/resource_match.cpp
> +    struct idset *ids = NULL;;
Oops. Thanks

2020-12-02 17:21 UTC, dongahn commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > std::numeric_limits<int>::max ()) {
I wanted to make this class as general as possible. I considered two ways. 1) make this class templated; or 1) use the largest data type. Going with 1) will have some side effects one of which is to have the implementations in header files. So for a little class like this, I thought it would be okay to go with 2). From our discussion yesterday, you seem to be okay with it. Unless I hear otherwise, I will keep this as is. Thanks.

2020-12-02 17:21 UTC, dongahn commented on t/scripts/flux-ion-resource.py
> +    def rpc_namespace_info (self, rank, type_name, Id):
I had no idea `id` was a keyword. I will go with `identity`.

2020-12-02 18:29 UTC, dongahn commented on resource/readers/resource_namespace_remapper.cpp
> +                                                           uint64_t>> ();
@milroy: Looking at the code, I am actually having a second thought.

It feels like doing this optimization will make the control flow more complex. It is like loop hoisting used in hot loop optimization. But this isn't a hotspot as this initial iteration happens only once per each execution target range (in a typical case, this would be called just once). So I have a slight preference to readability (with simpler control flow) over minor performance improvement.

Thoughts?

2020-12-03 22:17 UTC, SteVwonder approved these changes
LGTM! Just some comments below, none of them are required.  Thanks @dongahn! Huge improvement for GPU users.

2020-12-03 22:17 UTC, SteVwonder commented on t/t1016-nest-namespace.t
> +
Minor typo in commit message: `shen` -> `when`

2020-12-03 23:06 UTC, dongahn commented on resource/readers/resource_namespace_remapper.cpp
> +    m_low = lo;
This is a private class, so its API (including the constructors) is only used by `resource_namespace_remapper_t`, which performs its argument validation at that level. https://github.com/flux-framework/flux-sched/blob/1c052e446bd33763b818697c6d37372b042cf07c/resource/readers/resource_namespace_remapper.cpp#L112

2020-12-04 02:59 UTC, milroy commented on resource/readers/resource_namespace_remapper.cpp
> +                                                           uint64_t>> ();
Since it's not a hotspot, it's probably better to lean toward readability.

2020-12-04 03:01 UTC, milroy approved these changes

2020-12-15 00:59 UTC, SteVwonder commented on resource/readers/resource_namespace_remapper.cpp
> +            }
Since you are using emplace, it is my understanding that you don't need the `find` or the `if`:

```suggestion
        auto ret = m_remap.emplace (exec_target_range,
                                    std::map<const std::string,
                                                std::map<uint64_t,
                                                         uint64_t>> ());
```

Also IIUC, `insert` and `emplace` only return false for `ret.second` when the element already existed in the map, not when there is a memory error, so if you keep those checks, I think `ENOMEM` is a misnomer.  `EEXISTS` might be better.  I'm basing this off the docs in cplusplus.com, so I very well may be wrong about that. [[1]](https://www.cplusplus.com/reference/map/map/emplace/) [[2]](https://www.cplusplus.com/reference/map/map/insert/)

2020-12-15 01:02 UTC, SteVwonder commented on resource/readers/resource_namespace_remapper.cpp
> +            }
Sorry, I see now that you are using the result of the find further down. So ignore my comment about not needing the `find`. Sorry about that.

The bit about `ENOMEM` still stands though.  Assuming that `ret.second` is only false when the element already exists (and not when out of memory), I don't think you need that check at all (the find already proved the element doesn't exist).

2020-12-15 01:13 UTC, dongahn commented on resource/readers/resource_namespace_remapper.cpp
> +            }
I considered `EEXIST` but that condition will never occur because of the enclosing condition: `if (m_remap_iter == m_remap.end ()) {`

So I used `ENOMEM` as catch-all. Maybe it is better to just not checking `ret.second` since it should not occur?

2020-12-17 07:28 UTC, SteVwonder commented on resource/readers/resource_namespace_remapper.cpp
> +            }
> Maybe it is better to just not checking ret.second since it should not occur?

Yeah, I would agree with that.  Your call though.  My previous approval still stands, so feel free to put MWP on this PR when you are happy with it.  It'll probably need a rebase too for the new GitHub actions to take affect (I'm still seeing Travis on the status of this).

2020-12-17 18:09 UTC, dongahn commented
FYI -- CI failed because flux-core picked up the comma separated list format fix for `CUDA_VISIBLE_DEIVCES`. I will quickly adjust the failing test. https://github.com/flux-framework/flux-core/pull/3376

2020-12-17 18:26 UTC, merged

2020-12-17 18:29 UTC, dongahn commented
Ok. that did the trick. Thanks @milroy and @SteVwonder for your thorough review!

2020-12-17 19:39 UTC, SteVwonder commented
Thanks @dongahn for putting this together!