[WIP] Implement unpack_at for JGF
flux-framework/flux-sched pull request #775
Opened 2020-11-26 01:04 UTC by milroy

This PR implements the `unpack_at()` function in the JGF reader as discussed in issue #767.  The work in this PR is a necessary component of `grow` with the RV1/JGF reader and complements PR #773. It also adds a subcommand to the `resource-query` utility to enable testing of `unpack_at()`.  Once more of the infrastructure is in place, we can add `unpack_at()` tests to `flux-ion-resource` as well.

`Unpack_at()` requires a vertex attachment point and a fully-qualified JGF subgraph as inputs.  In this context, fully qualified means that the subgraph contains the root vertex and all intermediate vertices between the root and the new vertices to be attached.  In other words, every vertex in the subgraph has a path to the root.  The implementation is robust and doesn't assume any ordering of the vertices or edges.  It iterates through the JGF subgraph vertices and adds vertices not present in the resource graph, keeping track of the added vertex ids with an `std::unordered_set`.  When iterating through the subgraph edges, it only adds edges where either the source or target vertices (or both) have been added, ensuring that pre-existing edges aren't re-added to the resource graph.

This PR is work in progress.

2020-11-26 01:20 UTC, milroy commented
Note that I will be adding additional tests to the testsuite as this PR evolves.

2020-12-02 04:01 UTC, milroy commented
@dongahn I've been creating more tests for CI and have a question about handling containment subsystem `in` edges.

I've been assuming that the JGF subgraph to be attached will have both `contains` and `in` edges.  However, if I pass a JGF with bidirectional edges to `update attach`, the traverser update here: https://github.com/flux-framework/flux-sched/blob/97b91cccc4b29a41cad41c3ab54bb9c24e811b3f/resource/utilities/command.cpp#L258
results in a segfault.  Is this expected behavior?  If so, should I handle it in `resource-query` by passing two JGFs to `update attach`: one with `contains` and `in` edges for `unpack_at ()`, and one with only `contains` edges for the `traverser->run ()` step?

2020-12-02 17:03 UTC, dongahn commented
@milroy: As we discussed, I am going to have a review pass with a goal to land this right after PR #773. Could you remove [WIP] label when you are ready?

2020-12-02 17:06 UTC, dongahn commented
> If so, should I handle it in resource-query by passing two JGFs to update attach: one with contains and in edges for unpack_at (), and one with only contains edges for the traverser->run () step?

No you shouldn't have to. There seems to be a logic in `run ()` that doesn't like a bidirectional edge. We should look into it.

2020-12-02 17:07 UTC, dongahn commented
If you pass a bidirectional JGF into the existing interface (plain `update`), does `run()` still crash?

2020-12-03 02:07 UTC, milroy commented
> If you pass a bidirectional JGF into the existing interface (plain `update`), does `run()` still crash?

Yes, it does crash:
```bash
$ resource/utilities/resource-query -L t/data/resource/jgfs/elastic/l2-full.json -F jgf -f jgf -S CA -P high
INFO: Loading a matcher: CA
resource-query> update allocate t/data/resource/jgfs/elastic/node-add-test.json 1 0 3600
Segmentation fault
```

2020-12-03 02:43 UTC, dongahn commented
Could you create an issue for this? Since this is a distinct problem, it would be ideal to address it as a separate PR then yours?

2020-12-03 03:17 UTC, milroy commented
@dongahn no problem!  I'll create an issue and get to work on a PR.

2020-12-03 03:23 UTC, milroy commented
>  I'll create an issue and get to work on a PR.

However, fixing the issue enables CI testing for `unpack_at ()`, so I can see an argument for fixing it in this PR.

2020-12-03 07:54 UTC, milroy commented
@dongahn I opened issue #782 to discuss the segfault, but the fix appears to be a one liner.  If that looks good to you I can add a commit to this PR.

2020-12-03 17:01 UTC, dongahn commented
Yes, that sounds great!

2020-12-04 03:03 UTC, milroy commented
I ran into another problem with the traverser update step and created issue #783 for discussion.  That issue needs to be solved before this PR can be reviewed.

2020-12-10 09:08 UTC, milroy commented
I've dropped the WIP tag and have added two CI tests.  As soon as I add the remaining tests this PR will be ready for review.

2020-12-11 01:37 UTC, milroy commented
This should be ready for your review, @dongahn and @SteVwonder.

2020-12-12 01:50 UTC, milroy commented
I forgot to add `find sched-now=allocated` to CI test 7, so I committed two fixups and rebased.  The PR is actually ready for review now.

2020-12-17 03:42 UTC, milroy commented
@dongahn and @SteVwonder: please hold off on your reviews.  While preparing the demo for our collaborators, I ran into a problem.

The `unpack_at ()` implementation in this PR currently clears all allocations from the resource graph while attaching the new subgraph.  I'm currently investigating this issue and will update the PR as soon as I have more information.

2020-12-17 21:39 UTC, milroy commented
I determined that when new vertices are added to the resource graph, all allocations are cleared.  

@dongahn and I discussed this during the weekly team meeting.  He suspected this problem is caused by the lack of a copy constructor for boost `vecS` vertices.  I've confirmed that preallocating a large number of vertices before populating the resource graph prevents this problem, which is consistent with the lack of copy constructor for vertices.

Let's pause this PR for now as we will need further, thorough investigation to determine how best to fix the problem.  I may delete this PR until we have a good solution.

2020-12-17 23:38 UTC, dongahn commented
Thanks @milroy. Just to be clear, please see https://github.com/flux-framework/flux-sched/blob/master/resource/schema/sched_data.cpp#L38

I mainly chose to do this because two reasons: 1) because there is no grow support needed, there will be no dynamic resizing and the schedule state won't be copied once the graph is initialized; 2) there is no "copy constructor" in planner (though it is C but it is a class style): https://github.com/flux-framework/flux-sched/blob/master/resource/planner/planner.h.

As we will want to be able to grow and shrink beyond the initialization in a future, it seems we will need to design this and break down the tasks a bit. 

I am also wondering if we can still land most of this PR by limiting the use case of this... (Let's chat)

2020-12-18 07:22 UTC, dongahn commented
> @dongahn and @SteVwonder: please hold off on your reviews. While preparing the demo for our collaborators, I ran into a problem.

@milroy: I will look at your PR tomorrow if you are okay. I want to see if some portion of this code can go in sooner rather than later because I suspect we will need it soon.

2020-12-18 07:53 UTC, dongahn reviewed
I had a bit of time so I had a cursory review. BTW, I really like how you structured your commits so that each commit only has one topic!

I will look more tomorrow but I wonder if this PR can go in sooner with having a label like "experimental feature" somewhere. Since it will just not be used in production use, it seems to make sense. Let's chat tomorrow.

2020-12-18 07:53 UTC, dongahn commented on t/data/resource/commands/elastic/cmds02.in
> +quit
Interestingly, my GitHub renderer added an error icon with "No new line at end of file".
<img width="739" alt="Screen Shot 2020-12-17 at 11 33 03 PM" src="https://user-images.githubusercontent.com/862123/102587144-3e6a8980-40c0-11eb-96c8-c27b4e1db7c3.png">

2020-12-18 07:53 UTC, dongahn commented on resource/utilities/command.cpp
> +"allocate | reserv | attach): "
It is not a part of you commit but I just see a typo in `reserv`. Perhaps you can correct it while you are on this line.

2020-12-18 07:53 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +                errno = EPROTO;
This is my fault. But errno should change to `EINVAL`. I just have a global whole sale change in my PR #787.

2020-12-18 07:53 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +int resource_reader_jgf_t::unpack_vertices (resource_graph_t &g,
First a cursory question before taking a deeper dive: I see you overloaded `unpack_vertices` and `unpack_edges`. How difficult would it be to unified these functions so that we can use one version for both `unpack` and `unpack_at`?

2020-12-20 02:48 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +                errno = EPROTO;
No problem!

2020-12-20 02:49 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +int resource_reader_jgf_t::unpack_vertices (resource_graph_t &g,
During our conversation yesterday we determined it wouldn't be difficult, and my tested solution indeed is straightforward.

2020-12-20 02:49 UTC, milroy commented on resource/utilities/command.cpp
> +"allocate | reserv | attach): "
Will do!

2020-12-21 00:42 UTC, milroy commented
> I will look more tomorrow but I wonder if this PR can go in sooner with having a label like "experimental feature" somewhere.

Should I update the PR title with [Experimental]?

@dongahn I believe I have addressed your comments, and have updated the PR to reflect them.  You can take another look whenever you get a chance.  

@SteVwonder go ahead with your review when you're ready.

2020-12-22 00:34 UTC, milroy commented
> First a cursory question before taking a deeper dive: I see you overloaded `unpack_vertices` and `unpack_edges`. How difficult would it be to unified these functions so that we can use one version for both `unpack` and `unpack_at`?

After making this change `unpack` and `unpack_at` are exactly the same (except for the vertex argument passed to `unpack_at`, which isn't used).  Should we just get rid of the `unpack_at` interface and just always use `unpack`?

2020-12-23 00:00 UTC, milroy commented
I've rebased to pick up the latest changes to master and included the changes we discussed at coffee time.  This is ready for another review @dongahn and @SteVwonder.

2021-01-13 01:14 UTC, dongahn requested changes

2021-01-13 01:14 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +        }
Should this be a new commit (e.g., removing an additional indentation)

2021-01-13 01:14 UTC, dongahn commented on resource/utilities/command.cpp
> +"allocate | reserve | attach): "
Like we chatted over phone, I believe adding "attach" as a first-class command (i.e., not a subcommand of update) would make the semantics of the `update` command a bit cleaner.

2021-01-13 01:14 UTC, dongahn commented on resource/utilities/command.cpp
> +    if (attach) {
And with the first class `attach` command, we won't have to introduce this control flow complexity.

2021-01-13 01:14 UTC, dongahn commented on resource/utilities/command.cpp
> +    if (!(subcmd == "allocate" || subcmd == "reserve" || subcmd == "attach")) {
Same

2021-01-13 01:14 UTC, dongahn commented on resource/utilities/command.cpp
> +        && (subcmd != "attach")) {
same

2021-01-13 01:14 UTC, dongahn commented on resource/utilities/command.cpp
> +    return update_run (ctx, args[2], buffer.str (), jobid, at, d, attach);
Same

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/jgfs/elastic/node-add-test-random.json
> +{"graph": {"nodes": [{"id": "359", "metadata": {"type": "core", "basename": "core", "name": "core30", "id": 30, "uniq_id": 359, "rank": -1, "exclusive": true, "unit": "", "size": 1, "paths": {"contai
My GitHub viewer shows an error as this doesn't have a new line.

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/jgfs/elastic/node-add-test.json
> +{"graph": {"nodes": [{"id": "329", "metadata": {"type": "core", "basename": "core", "name": "core0", "id": 0, "uniq_id": 329, "rank": -1, "exclusive": true, "unit": "", "size": 1, "paths": {"containm
My GitHub viewer shows an error as this doesn't have a new line.

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/jgfs/elastic/node-test.json
> +{"graph": {"nodes": [{"id": "221", "metadata": {"type": "core", "basename": "core", "name": "core0", "id": 0, "uniq_id": 221, "rank": -1, "exclusive": true, "unit": "", "size": 1, "paths": {"containm
My GitHub viewer shows an error as this doesn't have a new line.

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/commands/elastic/cmds01.in
> +update attach @TEST_SRCDIR@/data/resource/jgfs/elastic/node-add-test.json 1 0 3600
Once `attach` is hoisted as a first class command, this will need an adjustment

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/commands/elastic/cmds02.in
> +update attach @TEST_SRCDIR@/data/resource/jgfs/elastic/node-add-test-random.json 1 0 3600
same

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/commands/elastic/cmds03.in
> +update attach @TEST_SRCDIR@/data/resource/jgfs/elastic/node-add-test.json 1 0 3600
same

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/commands/elastic/cmds04.in
> +update attach @TEST_SRCDIR@/data/resource/jgfs/elastic/node-add-test.json 1 0 3600
same

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/commands/elastic/cmds05.in
> +update attach @TEST_SRCDIR@/data/resource/jgfs/power.json 1 0 3600
same

2021-01-13 01:14 UTC, dongahn commented on t/data/resource/commands/elastic/cmds06.in
> +update attach @TEST_SRCDIR@/data/resource/jgfs/elastic/node-test.json 1 0 3600
same

2021-01-13 01:19 UTC, dongahn commented
@milroy: also, I think there is huge differences between being about to attach a subgraph (grow) before the traverser initialized the graph or after the initialization: https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu.hpp#L79. How are you handling the reinitialization (e.g., pruning filter installation etc) as part of the attach operation?

2021-01-13 07:19 UTC, milroy commented on resource/utilities/command.cpp
> +"allocate | reserve | attach): "
Sure thing!

2021-01-13 07:20 UTC, milroy commented on t/data/resource/jgfs/elastic/node-add-test-random.json
> +{"graph": {"nodes": [{"id": "359", "metadata": {"type": "core", "basename": "core", "name": "core30", "id": 30, "uniq_id": 359, "rank": -1, "exclusive": true, "unit": "", "size": 1, "paths": {"contai
Ok, I'll double check the new lines in the JSON files.

2021-01-13 07:44 UTC, milroy commented
> @milroy: also, I think there is huge differences between being about to attach a subgraph (grow) before the traverser initialized the graph or after the initialization: https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu.hpp#L79. How are you handling the reinitialization (e.g., pruning filter installation etc) as part of the attach operation?

Thanks for the feedback!  This is a good point, and I must admit I didn't consider the reinitialization.  However, I think I have a solution that's fairly straightforward and doesn't require reinitializing the whole resource graph.  It will require creating a temporary boost subgraph (as I tried to avoid before).  Then I can overload `initialize` which will take the original resource graph as an argument.  `Initialize` will call an overloaded `dfu_impl_t::prime_pruning_filter` which will traverse the *temporary* subgraph, but update or initialize `subplans` depending on whether the vertex is new or already existed in the *original* resource graph.  This will also require an addition to `planner_multi` that sets the new counts (a setter similar to `planner_multi_resource_total_by_type`).

Let's talk about this during a coffee time.

2021-01-15 02:27 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +        bool found = false;
Since `&&` is guaranteed to short circuit, this should be safe.

2021-01-16 02:03 UTC, milroy commented
After my discussions with @dongahn I've decided to implement the simplest (yet inefficient) way to initialize the added resource subgraph.  The updates to this PR add the capability of reinitializing the entire resource graph, which includes the new subgraph.  Since the process recreates subtree plans, allocated and reserved jobs may be affected.  I've added a check in `resource-query` to exit if there are outstanding allocations or reservations.

This is ready for another review.

2021-01-18 04:33 UTC, milroy commented
I broke out a line-wrap change into a new commit and made some minor edits to commit messages.

2021-01-20 07:33 UTC, dongahn approved these changes
@milroy: this LGTM! I have added a few minor comments, which would be good to be addressed before this is landed. But since they are minor, I approve this PR. 

@SteVwonder: would you want to take a look at this PR as well?

2021-01-20 07:33 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +        if ( (v = vtx_in_graph (m, fetcher.paths)) == null_vtx) {
Perhaps you can add a simple comment like:
```c++
// If the graph doesn't have the vertex, add it
```

2021-01-20 07:33 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +            added_vtcs.insert (std::string (fetcher.vertex_id));
```suggestion
            auto res = added_vtcs.insert (std::string (fetcher.vertex_id));
            if (!res.second) {
                errno = EEXIST;
                goto done;
            }
```

2021-01-20 07:33 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +        else {
```suggestion
        } else {
```

2021-01-20 07:33 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +                                        const vtx_t &v,
```suggestion
                                       vtx_t v, 
```

`vtx_t` is a native integer data type and this doesn't need to be `const` ref.

2021-01-20 07:33 UTC, dongahn commented on resource/readers/resource_reader_jgf.cpp
> +              || (added_vtcs.count (target) == 1)) {
Maybe you can add an one-line comment about this condition? 
```c++
// We only unpack the edge when it connects at least one newly added vertex 
```

2021-01-20 07:33 UTC, dongahn commented on resource/readers/resource_reader_jgf.hpp
> +    int update_vmap (std::map<std::string, vmap_val_t> &vmap, const vtx_t &v,
```suggestion
    int update_vmap (std::map<std::string, vmap_val_t> &vmap, vtx_t v,
```

2021-01-21 01:53 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +            added_vtcs.insert (std::string (fetcher.vertex_id));
I'll be sure to implement this change.

2021-01-21 01:57 UTC, milroy commented
@dongahn, thanks for the helpful suggestions!  I'll implement them and push the fixes. @SteVwonder let me know if you want to look this PR over as well.

2021-01-21 16:48 UTC, dongahn commented
> @dongahn, thanks for the helpful suggestions! I'll implement them and push the fixes. @SteVwonder let me know if you want to look this PR over as well.

@milroy: very nicely done and those position us very well for ultimately elasticity! Thanks you. 

@SteVwonder: it would be great to land this to our next release (Jan release). I believe this only needs just one more cursory release.

2021-01-22 22:00 UTC, SteVwonder reviewed
Thanks @milroy for putting this together.  This is a huge leap in functionality.  I'm super excited to see it in action :) Just two question below:

2021-01-22 22:00 UTC, SteVwonder commented on resource/readers/resource_reader_jgf.cpp
> +    std::unordered_set<std::string> added_vtcs;
Is this used by later commits?  If not, can you elaborate on the addition of this into the unpack_* function interfaces?

2021-01-22 22:00 UTC, SteVwonder commented on t/t3028-resource-grow.t
> +    ${query} -L ${jgf} -F jgf -f jgf -S CA -P low -t 007.R.out \
In the case of a nonexistent JGF, I think `resource-query` should exit with a non-zero exit code, right?  (Same for invalid argument and trying to grow when there are allocations).  If so, then A) I think `resource-query` isn't exiting with non-zero status and needs to be updated to do so B) this test should use `test_must_fail`.

2021-01-22 22:05 UTC, dongahn commented on t/t3028-resource-grow.t
> +    ${query} -L ${jgf} -F jgf -f jgf -S CA -P low -t 007.R.out \
@SteVwonder: I can take this. `resource-query` is designed to be an interactive CLI, it will be difficult to cause it to return on this condition. Certain the new command can return -1, which then cause the CLI to exit but that probably isn't what users want. At interactive prompt, when a user sees the error message from the command, he/she may want to correct the error (e.g., provide the correct path) and retry...

2021-01-22 22:31 UTC, milroy commented on resource/readers/resource_reader_jgf.cpp
> +    std::unordered_set<std::string> added_vtcs;
The `unordered_set` is used primarily here: https://github.com/flux-framework/flux-sched/blob/b8cce32e4251ea8c3f2394157410667543b2a4ef/resource/readers/resource_reader_jgf.cpp#L763 

and here: https://github.com/flux-framework/flux-sched/blob/b8cce32e4251ea8c3f2394157410667543b2a4ef/resource/readers/resource_reader_jgf.cpp#L880

for _O(1)_ insertion and lookups of the vertices in the new JGF subgraph that are not present in the original resource graph.  By keeping track of the new vertices, we can add only the new edges as well (i.e. those that connect at least one new vertex).  If we didn't do this, we would end up re-adding edges that already exist in the resource graph, with likely unintended consequences.  The `added_vtcs` will likely be used by future optimizations for traversing and initializing only the newly added subgraph (rather than the entire, updated resource graph).

2021-01-22 22:36 UTC, milroy commented
Thanks for the review and comments @SteVwonder!  Let me know if you need more details and if you'd like me to make changes before this gets merged.

2021-01-22 22:39 UTC, SteVwonder approved these changes
LGTM! Thanks @milroy!

2021-01-22 22:42 UTC, milroy commented
> LGTM! Thanks @milroy!

Great, thanks to you and @dongahn!  I'm going to rebase and set MWP.

2021-01-22 22:49 UTC, dongahn commented
Great job @milroy and @SteVwonder. Thanks!

2021-01-22 22:54 UTC, merged