Globally rename "administrative priority" to "urgency"
flux-framework/flux-sched pull request #781
Opened 2020-12-02 21:42 UTC by chu11

Per RFC21 update (flux-framework/rfc#277) the "administrative priority" has been renamed to "urgency".

Globally update flux-sched for this change. This is built on and dependent on https://github.com/flux-framework/flux-core/pull/3394

2020-12-02 21:50 UTC, dongahn requested changes
Thanks. I made some suggestions about use of urgency vs. priority. I think we should stick with priority when we refer to a case where both urgency and submit time is considered. Otherwise, use of urgency seems good.

2020-12-02 21:50 UTC, dongahn commented on qmanager/policies/queue_policy_bf_base_impl.hpp
> +            // High-urgency job has been reserved, continue
In this case, "high-priority" is right, taking into account both urgency and submit time.

2020-12-02 21:50 UTC, dongahn commented on t/Makefile.am
> +    t1013-qmanager-urgency.t \
I have slight preference to stick with priority because this tests job "priority" as determined by urgency _and_ submit time.

2020-12-02 21:50 UTC, dongahn commented on t/t1013-qmanager-urgency.t
> +test_expect_success 'urgency: loading fluxion modules works' '
We should keep "priority" as the test label still?

2020-12-02 21:50 UTC, dongahn commented on t/t1013-qmanager-urgency.t
> +test_expect_success 'urgency: a full-size job can be scheduled and run' '
Same as above

2020-12-02 21:50 UTC, dongahn commented on t/t1013-qmanager-urgency.t
> +test_expect_success 'urgency: 2 jobs with higher urgency will not run' '
```suggestion
test_expect_success 'priority: 2 jobs with higher urgency will not run
```

2020-12-02 21:50 UTC, dongahn commented on t/t1013-qmanager-urgency.t
> +test_expect_success 'urgency: canceling the first job starts the last job' '
Same as above

2020-12-02 21:50 UTC, dongahn commented on t/t1013-qmanager-urgency.t
> +test_expect_success 'urgency: cancel all jobs' '
Same

2020-12-02 21:50 UTC, dongahn commented on t/t1013-qmanager-urgency.t
> +test_expect_success 'urgency: removing fluxion modules' '
Same

2020-12-02 23:52 UTC, chu11 commented
@dongahn thanks for the review.  I wasn't 100% sure on some of the cases.  I've re-pushed with changes based on your comments above.

2020-12-03 01:12 UTC, dongahn commented
> usage: flux-mini [-h] {run,submit,batch,alloc} ...
2132flux-mini: error: unrecognized arguments: --urgency
2133not ok 3 - priority: a full-size job can be scheduled and run

CI tests failed with the following. Probably the urgency changes have not been merged in flux-core yet. Also, do we need to specify the urgency with `=`? `--urgency=5` as opposed to `--urgency 5`. The latter might work as well though.

2020-12-03 01:16 UTC, chu11 commented
yeah, this depends on PR https://github.com/flux-framework/flux-core/pull/3394 being merged first.

2020-12-04 20:17 UTC, grondo commented
Restarted the build now that flux-framework/flux-core#3394 is merged and docker images have been updated.

2020-12-04 20:57 UTC, grondo commented
@dongahn want to give this one an approval?

The "check flux-sched" CI tests in flux-core will all fail until this PR is merged.

2020-12-04 21:37 UTC, grondo approved these changes
LGTM, and a cursory examination shows you've addressed all of @dongahn's comments, so I'll approve so we can get this in.

2020-12-04 21:37 UTC, grondo commented
Ok to set MWP @chu11?

2020-12-04 22:04 UTC, dongahn commented
Sorry I am late. Yes, this is good to go and I will add MWP.

2020-12-04 22:05 UTC, dongahn approved these changes

2020-12-04 22:12 UTC, merged