qmanager: update per libschedutil API changes
flux-framework/flux-sched pull request #801
Opened 2021-01-13 18:46 UTC by chu11

Changes per `libschedutil` changes in https://github.com/flux-framework/flux-core/pull/3447

We should wait for changes upstream to be accepted before merging this of course.

These commits could be collapsed into fewer ones if desired.

2021-01-13 20:17 UTC, dongahn commented on qmanager/policies/base/queue_policy_base.hpp
> +    unsigned int urgency = 0;
Is what passed to this layer through schedutil "priority" or "urgency"? If "priority", we should change the field name to priority?

2021-01-13 20:17 UTC, dongahn commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
This is more of a question.

So this callback is called when there is a priority change of a pending job? Will this be currently called back (if installed) if a user change the urgency at all?

2021-01-13 20:21 UTC, chu11 commented on qmanager/policies/base/queue_policy_base.hpp
> +    unsigned int urgency = 0;
yes it's priority.  The urgency -> priority change is what i described in issue #798.  I have a branch with it done that goes on top of this.  If you'd like, I could just add it on top of this PR?  Or perhaps it should go in before this PR.

2021-01-13 20:24 UTC, chu11 commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
> So this callback is called when there is a priority change of a pending job?

yes

> Will this be currently called back (if installed) if a user change the urgency at all?

By "currently", I'm not sure if you mean the current `flux-core` master?  If so yes, b/c currently `priority` == `urgency`, so an urgency change would lead to this being called.   Longer out, when the priority plugin is created, it'll be called if the priority plugin calculates a different priority.

2021-01-14 01:32 UTC, chu11 commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
per our offline discussion, trying to implement `prioritize_cb`, but it's not obvious to me how to do this given the current `queue` implementation.  I feel I should be doing something like this:

```
job = queue->lookup (id);
queue->take_off_queue (job);
job->priority = 4294967295 - priority;
queue->insert (job);
```

but I can't find how to do `take_off_queue`.  `remove` seems to alter some internal state of the `queue` so don't want to do that.  `pending_pop()` only seems to pop the front of the queue.  Not sure if I'm missing something.

2021-01-14 05:03 UTC, chu11 commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
Ahhh I figured out the trick.  `remove()` does in fact do more than just `remove` from the queue (which initially made me think it wasn't safe to use), but as long as we `insert` it back, everything will be reset back to the way it should be.

2021-01-14 05:12 UTC, chu11 commented
rebased and re=pushed per discussion above

- Added fix for #798 
- Added a `prioritize_cb` and tests
-

2021-01-14 05:36 UTC, dongahn commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
chu11@: sched's queue uses `std::map` so `insert()` and other command operations are `O(N)`

2021-01-14 05:53 UTC, dongahn commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
The current abstraction for `queue` base is that it manages jobs through multiple queues, pending queues, running queues, complete queues as each job is going through its lifecycle. So use of `remove()` might be a bit too error prone. Perhaps we should add a new method specifically targeting modifying an existing job if certain conditions are met...

2021-01-14 06:06 UTC, dongahn commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
maybe `pending_modify()` or `pending_repriotize()` somewhere around: [here](https://github.com/flux-framework/flux-sched/blob/master/qmanager/policies/base/queue_policy_base.hpp#L121)

2021-01-14 17:14 UTC, chu11 commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
sounds good, i'll add a new member function of that nature.

2021-01-14 19:20 UTC, chu11 commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
since we're now adding a `pending_reprioritize()` to the queue data structure, it's probably best to spin the initial prioritize_cb into a new PR, as the work in clearly increasing beyond this PR.

2021-01-14 19:25 UTC, chu11 commented
> Added a prioritize_cb and tests (I could squash this into an earlier commit that simply set .prioritize to NULL)

Since we're now adding new member functions into the queue policy implementation, the initial `prioritize_cb` implementation should be split off into a new PR.  Commits related to that prior work have been removed.

2021-01-14 19:56 UTC, dongahn commented on qmanager/modules/qmanager.cpp
> +    .prioritize = NULL,
Sounds good as agreed at our meeting!

2021-01-14 22:43 UTC, dongahn commented
@Mergifyio rebase

2021-01-14 22:59 UTC, dongahn requested changes
This looks great to me. Just one minor nit. The CI is failing because the corresponding flux-core hasn't landed, correct?

2021-01-14 22:59 UTC, dongahn commented on qmanager/modules/qmanager_callbacks.cpp
> +        errno = EPROTO;
```suggestion
        errno = ENOMEM;
```

2021-01-14 23:00 UTC, chu11 commented
> The CI is failing because the corresponding flux-core hasn't landed, correct?

Yeah, compilation should fail at this point.

2021-01-15 00:18 UTC, chu11 commented
rebased & re-pushed per your comments above @dongahn.

If you think this looks good, then we can merge https://github.com/flux-framework/flux-core/pull/3447 and then merge this, as @garlick has approved the flux-core PR.

2021-01-15 00:28 UTC, dongahn commented
@chu11: sounds good to me. Go ahead and merge flux-core PR and I will merge this in.

2021-01-15 00:29 UTC, dongahn commented
@mergefyio rebase

2021-01-15 00:29 UTC, dongahn commented
@Mergifyio rebase

2021-01-15 03:28 UTC, chu11 commented
@mergefyio rebase

2021-01-15 03:30 UTC, chu11 commented
@Mergifyio rebase

2021-01-15 04:20 UTC, dongahn approved these changes

2021-01-15 04:21 UTC, merged