qmanager: support re-prioritization of jobs
flux-framework/flux-sched pull request #803
Opened 2021-01-14 20:21 UTC by chu11

Support re-prioritization of pending jobs by adding a prioritize callback through `libschedutil`.

Built on top of PR #801

2021-01-14 23:23 UTC, dongahn requested changes
Generally LGTM. I left a few minor change suggestions.

2021-01-14 23:23 UTC, dongahn commented on qmanager/modules/qmanager_callbacks.cpp
> +        if (queue->pending_reprioritize (id, 4294967295 - priority) < 0) {
`4294967295 - priority` patterns seem to appear over and over again. Perhaps this should be refactored  somewhere so we only need to change one line if the max priority change once again for some reason. Any idea for refactoring? This shouldn't keep this PR from being merged though. If we don't want to address this now, we should open an issue ticket so that this can be refactored later.

2021-01-14 23:23 UTC, dongahn commented on qmanager/modules/qmanager_callbacks.cpp
> +        flux_log (h, LOG_DEBUG, "%s (id=%jd)", "priority changed",
This might generate too many debug output when we add a fairshare priority plug in since it print one line per updated job?

2021-01-14 23:23 UTC, dongahn commented on qmanager/modules/qmanager_callbacks.cpp
> +                continue;
It would be good to handle either errno with distinct error message?

`errno=ENOENT` would typically mean that there was a race condition: when a priority change was requested right before fluxion responds to alloc request. In this case, users might be interested in know why, we may want to log a message. 

`errno=EINVAL` means the upper layer requested a invalid priority and this suggests a bug somewhere. We will want to log an error message.

2021-01-15 01:54 UTC, chu11 commented
re-pushed with fixes per comments above.  I added a new `calc_priority()` function in `qmanager_callbacks.cpp` to do the common priority calculation.  I considered if it should be in the `queue_policy` data structure, but since `job->priority` is public, there's probably no point to trying to abstract the setting of the priority internally to `queue_policy`.

2021-01-15 02:49 UTC, dongahn commented
> re-pushed with fixes per comments above. I added a new calc_priority() function in qmanager_callbacks.cpp to do the common priority calculation. I considered if it should be in the queue_policy data structure, but since job->priority is public, there's probably no point to trying to abstract the setting of the priority internally to queue_policy.

Yes, that is exactly what I was thinking about. The architecture is such that you put flux specific things to the module code and generic code in elsewhere. The queue layer is designed so that it can be layered with 3rd party (e.g., Kubernetes)  if they want.

2021-01-15 05:32 UTC, chu11 commented
oops, noticed some English errors on some comments, re-pushed

2021-01-20 07:45 UTC, dongahn approved these changes
@chu11: Is this ready to be merged? I've added a few minor comments. But since those are minor, I approve this PR. When you are ready, feel free to add the MWP label.

2021-01-20 07:45 UTC, dongahn commented on qmanager/policies/base/queue_policy_base_impl.hpp
> +         static_cast<double> (job->t_stamps.pending_ts)}, job->id));
```suggestion
    auto res = m_pending.insert (std::pair<std::vector<double>, flux_jobid_t> (
                   {static_cast<double> (job->priority),
                    static_cast<double> (job->t_submit),
                    static_cast<double> (job->t_stamps.pending_ts)}, job->id));
    if (!res.second) {
        errno = EEXIST;
        goto out;
    }
```

2021-01-20 07:45 UTC, dongahn commented on qmanager/policies/base/queue_policy_base.hpp
> +     *                       EINVAL: job not pending
It will be a very unusual error but you would need to document:
`errno=EEXIST` if you follow one of my error handling suggestion for `map::insert`.

2021-01-20 17:59 UTC, chu11 commented
yup, ready for merging.  Added your tweaks.  Using `auto res` messed up the use of `goto out` (the `crosses initialization` error), but since we don't have to do any cleanups, just replacing w/ `return -1` was an easy fix.

2021-01-20 18:43 UTC, chu11 commented
appeared to hit #800, didn't want to restart builder if someone wanted to take look at it?

2021-01-20 18:51 UTC, dongahn commented
It is on my list. Feel free to restart.

2021-01-21 21:40 UTC, chu11 commented
setting MWP per @dongahn conversation

2021-01-21 21:41 UTC, merged

2021-01-22 00:10 UTC, dongahn commented
Thanks @chu11!