Add async FCFS policy support and other scheduling optimization
flux-framework/flux-sched pull request #826
Opened 2021-04-29 05:07 UTC by dongahn

This PR adds a few scheduling optimization.

- Add delay scheduling optimization: it moves the invocation of the scheduling loop into prepare/check watcher callbacks so that rapidly submitted jobs will have a chance to be enqueued before they are considered in the loop. This allows for bulk processing;
- Add multi-match support: a match_multi stream RPC can take in multiple job requests, run a match for each job request and reply each matching result to the sender. This helps reduce the overheads associated with singleton match RPC.
- Limit annotation update only upto queue-depth;
- Add async multi-match support into the high-level resource API;
- Migrate FCFS queue policy to async execution.

2021-04-29 05:19 UTC, dongahn commented
@SteVwonder: this should be ready for your review.

2021-04-29 16:22 UTC, dongahn commented
@SteVwonder: Sorry -- I just found one missing change. Let me add that and force a push unless you started your review.

2021-04-29 16:46 UTC, dongahn commented
Ok. I pushed that one line change and squashed.

2021-04-30 05:40 UTC, dongahn commented
Filed one issue against flux-core, which I found during the testing of this PR on Quartz at a larger scale than my dev environment: https://github.com/flux-framework/flux-core/issues/3625

2021-05-04 00:18 UTC, SteVwonder requested changes
Thanks @dongahn for putting this together. This will have huge performance benefits, especially for large bursts of jobs.  I left a few inline comments.  I also have one overarching comment w.r.t. the tracking of the scheduler loop being idle or active:

Currently, the setting of the scheduler loop being active is spread across three different files (reapi, fcfs_impl, and bf_impl) and it is done using two different interfaces (`set_sloop_active` and `set_sched_loop_active`).  The getting of this value is done in a fourth file (qmanager_callbacks) but only via one of the getter interfaces (`is_sched_loop_active`).  This distribution of the logic across many files (and layers of the scheduler) makes it harder to reason about the control flow and think through possible edge cases.  I commented in a few places where I think there are edge cases, but I'm not sure those are correct and I'm also not sure I've been able to enumerate all of the possible edge cases.

I think going forward, this will be tricky to maintain and easy for bugs to creep in (especially with the more exotic multi/batching that is possible with hybrid backfilling).  Fortunately, I **think** it would be possible to push most of this logic (at least the setting part) into a single layer (reapi).  If so, I think that would make reasoning about and maintaining that logic much easier.  Thoughts?

2021-05-04 00:18 UTC, SteVwonder commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +        // schedulable.
I think I'm missing something pretty big here.  I'm confused by this comment and the git commit message.  My understanding is that the behavior you are trying to avoid is the intended behavior.  Once you hit the queue depth limit, the scheduling loop should stop and not try again until either a new job is submitted (and even then, it would technically need to be insert at a depth in the queue higher than the limit) or resources are freed by a currently running job.  Even before batching, my understanding is that it should never have been possible for a job deeper in the queue than the queue depth to be scheduled.

With this code as it is written, my understanding is that (assuming no new jobs are submitted and no jobs finish) on the next check/prep/idle loop, the scheduling loop will run again, but it will consider the exact same set of jobs that it just considered.  This means that the scheduler will always be active and never not be trying to schedule jobs when the number of pending jobs > queue depth. Is that correct?

2021-05-04 15:30 UTC, dongahn commented
> Currently, the setting of the scheduler loop being active is spread across three different files (reapi, fcfs_impl, and bf_impl) and it is done using two different interfaces (set_sloop_active and set_sched_loop_active). The getting of this value is done in a fourth file (qmanager_callbacks) but only via one of the getter interfaces (is_sched_loop_active). This distribution of the logic across many files (and layers of the scheduler) makes it harder to reason about the control flow and think through possible edge cases. I commented in a few places where I think there are edge cases, but I'm not sure those are correct and I'm also not sure I've been able to enumerate all of the possible edge cases.

> I think going forward, this will be tricky to maintain and easy for bugs to creep in (especially with the more exotic multi/batching that is possible with hybrid backfilling). Fortunately, I think it would be possible to push most (all?) of this logic into a single layer (reapi). If so, I think that would make reasoning about and maintaining that logic much easier. Thoughts?

I struggled with this myself as well. reapi isn't the right layer. But it may be possible to make `queue_policy_base_t` a subclass of the newly added the `queue_adapter_base_t` class. Let me try.

2021-05-04 15:33 UTC, dongahn commented on resource/modules/resource_match.cpp
> +    }
I think I tried `o` and that didn't work. Let me try again.

2021-05-04 15:37 UTC, dongahn commented on resource/modules/resource_match.cpp
> +
Nice catch! Thanks.

2021-05-04 15:39 UTC, dongahn commented on qmanager/modules/qmanager_callbacks.cpp
> +             qd++;
`qd` wasn't set initially in the for loop head though. I can move that to the header as well for consistency.

2021-05-04 15:39 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi.hpp
> +     *  is expected to dequeue the the job from its pending queue
Good catch!

2021-05-04 15:39 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi.hpp
> +     *                       Others: one that can raised from match_multi RPC
Any `errno` that can come from the call chains of `run_match`.

2021-05-04 15:42 UTC, dongahn commented on qmanager/policies/queue_policy_fcfs.hpp
> +    virtual void set_sloop_active (bool active);
I struggled with this because this class inherits from two abstract class: `queue_base_t` and the new `queue_adapter_base_t`, which is a way to adapt the abstract queue to the `reapi` without exposing too details of queue at all. I will see if this can be handled by the bottom most base queue class.

2021-05-04 15:46 UTC, dongahn commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +    }
I think the thought was this method could be called from another continuation function. Since this is a implementation of the "public" class method from `queue_adapter_base_t`, I do think it makes sense to do error checking at this level for future use.

2021-05-04 16:16 UTC, dongahn commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +        // schedulable.
Yeah I had to think about this myself as well. `queue-depth` is an optimization so that each schedule loop invocation will consider pending jobs only up to the queue depth. This way, the scheduler will not block too long going through all pending jobs in an unbounded manner. 

Now, if a loop invocation terminated with "no later jobs can be scheduled", yes the queue should become no longer schedulable and we should not invoke the loop again and again going over the exact sequence of pending jobs until the next job or resource event arises. I believe the code handles this correctly.

However, if the loop terminated with the queue-depth limit hit, the loop should still remain schedulable and the next time the loop is invoked, it should consider the next set of jobs in order to avoid starvation under our new `delay scheduling`

Imagine an extreme case where all M jobs are enqueued before we see the first invocation of the schedule loop, which terminated scheduling only queue-depth number of pending jobs (where M >> queue-depth). Because there will be no further "job" event (which we typically see from "non delay scheduling"), the schedule loop will not be invoked again until the first set of jobs finish, which can be a long time. This is a starvation that we probably don't want to see.

2021-05-04 16:16 UTC, dongahn commented on resource/modules/resource_match.cpp
> +                        __FUNCTION__, static_cast<intmax_t> (jobid));
Good idea. W/ the current queuing policy, this info is still available at the queue policy level. But including such debug info more explicit makes sense to me.

2021-05-04 16:19 UTC, dongahn commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +    if (pack_jobs (jobs) < 0)
Yes we are on the same page. For now, we should control this behavior with queue-depth parameter. How about changing the limit to 32 as part of this PR?

2021-05-04 17:35 UTC, dongahn commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +    if (pack_jobs (jobs) < 0)
https://github.com/flux-framework/flux-sched/issues/830 opened to track this.

2021-05-04 17:43 UTC, dongahn commented on qmanager/policies/base/queue_policy_base_impl.hpp
> +            m_pending_provisional.erase (
Agreed. I will add a conditional statement with `errno=ENOENT` in this case. But won't log since that should be handled by the upper layer.

2021-05-04 17:47 UTC, dongahn commented on qmanager/policies/base/queue_policy_base_impl.hpp
> +    sz = m_pending.erase (
Wow. This is actually a merge error from git rebase... Will fix!

2021-05-04 17:52 UTC, dongahn commented on qmanager/policies/base/queue_policy_base_impl.hpp
> +    } else {
@SteVwonder: thank you for catching this! yes this is a bug and crept up during that merge issue as well.

2021-05-04 17:58 UTC, dongahn commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +        // schedulable.
I will mark it resolved. If you disagree, let me know.

2021-05-04 18:04 UTC, SteVwonder commented on qmanager/policies/queue_policy_fcfs_impl.hpp
> +        // schedulable.
AH! That makes sense.  Thanks for taking the time to explain.  Good catch!

2021-05-05 02:02 UTC, dongahn commented on resource/modules/resource_match.cpp
> +    }
`O` doesn't seem to work either.

2021-05-05 02:02 UTC, dongahn commented
@SteVwonder: I believe I have addressed all of your requests. Please take a quick look at the new commits. Once you are okay, I will squash the intermediate commits.

2021-05-05 23:05 UTC, SteVwonder approved these changes
LGTM! Thanks @dongahn

2021-05-06 00:06 UTC, merged