Using static_cast to ensure type compatibility in readers.
flux-framework/flux-sched pull request #858
Opened 2021-09-07 15:38 UTC by ksuarez1423

Potential fix for #856. Cannot currently compile master version of flux-sched, and instead have compiled 0.16.0 with this change. There is a slight difference between these versions in the readers, but the bug remains the same -- regardless, the change to this particular version is untested. However, to the best of my knowledge, this will ensure that type differences do not prevent compilation on platforms using GCC.

2021-09-07 15:52 UTC, dongahn requested changes

2021-09-07 15:52 UTC, dongahn commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > static_cast<uint64_t>(std::numeric_limits<int>::max ())) {
```suggestion
                if (remap_id 
                        > static_cast<uint64_t> (std::numeric_limits<int>::max ())) {
```

2021-09-07 15:52 UTC, dongahn commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > static_cast<uint64_t>(std::numeric_limits<int>::max ())) {
A code style suggestion and super minor nit. Please notice the whitespace for `static_cast`. The same comment apply below lines as well.

2021-09-07 17:26 UTC, ksuarez1423 commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > static_cast<uint64_t>(std::numeric_limits<int>::max ())) {
Made suggested change in all locations -- although, one of the locations uses remap_rank, and I may have misunderstood the suggestion for that spacing.

2021-09-10 23:14 UTC, dongahn commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > static_cast<uint64_t>(std::numeric_limits<int>::max ())) {
Looks great. Could you squash the last commit with the first and force a push since we don't want to keep interim commits?

2021-09-14 19:45 UTC, ksuarez1423 commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > static_cast<uint64_t>(std::numeric_limits<int>::max ())) {
Sorry for the wait, @dongahn -- I think I've gotten it right?

2021-09-14 19:46 UTC, SteVwonder commented on resource/readers/resource_reader_hwloc.cpp
> +                if (remap_id > static_cast<uint64_t>(std::numeric_limits<int>::max ())) {
The squash LGTM!

2021-09-14 19:48 UTC, SteVwonder approved these changes
LGTM! Thanks @ksuarez1423!

2021-09-15 05:31 UTC, merged