[WIP] HLAPI: add CLI initialization and implement match_allocate, cancel, and info
flux-framework/flux-sched pull request #888
Opened 2021-11-18 03:30 UTC by milroy

This PR adds new capability to the Fluxion C/C++ CLI resource HLAPI so that clients such as KubeFlux can initialize a Fluxion context (and maintain it in an external binding).  This PR implements the `match_allocate`, `cancel`, and `info` functions which KubeFlux needs first.  Other HLAPI functions can be implemented in straightforward analogy to the changes in this PR.

Data structures such as `resource_ctx_t` and `resource_params_t` are defined as in `resource-query` and provide a foundation for the `reapi_cli`.  Note that the implementation of `reapi_cli_info` changes the public API to add a mode argument that returns the job status.

Since the `resource_ctx_t` is created as a raw pointer (as distinct from `resource_query` where it's a `std::shared_ptr`) , a threaded client must be careful how it consumes the API.  

This PR is WIP since the most appropriate pointer type and how to perform CI testing is still to be determined.

2021-11-18 03:38 UTC, dongahn commented
@milroy: Great start! I know it is a WIP PR. Just let me know when you want me to give the first round of review.

2021-11-18 04:51 UTC, cmisale commented on resource/hlapi/bindings/c/reapi_cli.h
> + *  \param mode      string containing the job state.
What is the meaning of `mode`?

2021-11-18 07:13 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.h
> + *  \param mode      string containing the job state.
It means the job state (`job_lifecycle_t`: INIT, ALLOCATED, RESERVED, CANCELED, ERROR).  I think this is important information for `info` to return.

2021-11-21 15:26 UTC, dongahn commented
> Since the resource_ctx_t is created as a raw pointer (as distinct from resource_query where it's a std::shared_ptr) , a threaded client must be careful how it consumes the API.

Yes. And passing the thread-safety responsibility to the caller is a great practice. Doing mutex within the API itself can open up a new can of worms.

2021-11-21 16:26 UTC, dongahn requested changes
@milroy: Thank you for putting this together. 

Here is the very first set of my review. 

I do want to spend some time to think about the context passing part of your PR a bit more. My suspicion is there would be a simpler scheme to achieve the context passing than the current scheme. 

But I am doing this while I am in transit, I don't know when  I can get to that and at the same time.

Stay tuned.

2021-11-21 16:26 UTC, dongahn commented on qmanager/modules/Makefile.am
> +    $(top_builddir)/resource/libresource.la \
I believe it would be best to maintain the minimum dependency between qmanager and resource layer. 

My suggestion would be just to keep the original jobspec library depedency and drop the following dependencies from `sched_fluxion_qmanager_la_SOURCES`:

```
    $(top_srcdir)/resource/hlapi/bindings/c++/reapi_cli.hpp \
    $(top_srcdir)/resource/hlapi/bindings/c++/reapi_cli_impl.hpp \
```

Or you can even remove that and create a library dependency to `libreapi_module.la` here and see that still resolves.

2021-11-21 18:03 UTC, milroy commented on qmanager/modules/Makefile.am
> +    $(top_builddir)/resource/libresource.la \
Unfortunately, there are dependencies on `reapi_cli_t` in ```queue_policy_factory_impl.hpp```, e.g.:
```C++
        if (policy == "fcfs") {
            if (reapi == "module")
                p = std::make_shared<queue_policy_fcfs_t<reapi_module_t>> ();
            else if (reapi == "cli")
                p = std::make_shared<queue_policy_fcfs_t<reapi_cli_t>> ();
        }
```

2021-11-21 18:04 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +    delete ctx;
Sure thing!

2021-11-21 18:21 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +        std::cerr << "Error allocating memory: " << e.what () << "\n";
Good suggestion.  I'll get to work on improving the error logging, and if it proves to be a blocker for this PR I will include it in a new one.

Do you think the public API should have a structured error message as part of the return or as an argument?

2021-11-21 18:25 UTC, milroy commented
@dongahn thanks for the helpful initial review during your travels!  I'll get to work on the items you identified and will wait for updates on the context passing.

2021-11-27 17:58 UTC, dongahn commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +        std::cerr << "Error allocating memory: " << e.what () << "\n";
I have been happy with the following style. If you meant an error catalogue with "A structured error message", I believe that's a bit overkill. Providing the client code with an error string right after some method would be good enough, I believe.

https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu.hpp#L42

https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu.hpp#L49

2021-11-27 17:59 UTC, dongahn commented on qmanager/modules/Makefile.am
> +    $(top_builddir)/resource/libresource.la \
Ah... You can get rid of that for now. The intent is to created a CLI test for `qmanager` as well but we don't have to worry about this for now.

2021-11-27 19:11 UTC, dongahn commented
> @dongahn thanks for the helpful initial review during your travels! I'll get to work on the items you identified and will wait for updates on the context passing.

We will need a more in-person discussion for context passing. But here is my observation so far. 

1. I find the current `reapi_cli_t` implementation slightly breaks the intended separation of concerns of `reapi_t`. The first implementation of `reapi_t` was based on `sched-fluxion-resource` module service. This meant that its methods (such as `match_allocate`) can be called without needing to instantiate a class object and thus the methods are all class static. Now I see your cli implementation of this class goes beyond this model: it also allocates and initialize san object (`resource_context_t`). 

2. I believe you can address this by introducing a new class: `resource_query_t` and instantiating a proper class object using that first and then passing the object into your `reapi_cli_t` as the first argument. In addition to tighter separation of concerns, another advantage  would be  that you can now avoid using file-scoped static functions like [this](https://github.com/flux-framework/flux-sched/pull/888/commits/1b49b41564a5ffcb971dd892fe2c2a4b83bd2403#diff-9c9eea1269c68f630ee4f9e098625e6499501abf7e4a570c55db642897027326R32). They now can be private methods of this new class. 

3. It was there in the beginning, but with the introduction of an additional derived class, I am concerned about the use of `void *` `reapi_t` : [void *](https://github.com/flux-framework/flux-sched/blob/master/resource/hlapi/bindings/c%2B%2B/reapi.hpp#L118). The intention was to pass an external arbitrary handle (e.g., `flux_t *`) into each API implementation. But `void *` can quickly become unwieldy with multiple class derivations. For this round, I believe we should at least introduce an abstract class support to avoid the use of `void *`. For example,

```c++

class match_service_handle_t {

};
```

The module api user will extend it:

```c++

class sched_fluxion_resource_t : public match_service_handle_t {
public:
    flux_t *h;
};
```

The cli api user will extend it:

```c++

class resource_query_t : public match_service_handle_t {

};
```

2021-11-30 19:26 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +        std::cerr << "Error allocating memory: " << e.what () << "\n";
What I meant by "structured error message" is similar to what the GitHub API returns, e.g., 
```json
{"msg":"User quota exceeded","max_allowed":10000,"administrator_id":1234}
```
where the message indicates the exception, value provided, and allowed values.

I'll implement the method used by the traverser for this PR. Thanks!

2021-12-04 01:36 UTC, milroy commented
@dongahn: I've made good progress implementing your suggestions regarding the context passing.  There is a wrinkle with your third item:

> It was there in the beginning, but with the introduction of an additional derived class, I am concerned about the use of void * reapi_t : void *. The intention was to pass an external arbitrary handle (e.g., flux_t *) into each API implementation. But void * can quickly become unwieldy with multiple class derivations. For this round, I believe we should at least introduce an abstract class support to avoid the use of void *. For example,

Implementing `match_service_handle_t` requires a fair number of modifications to qmanager policies, as it passes `flux_t` handles around as `void*` (which need to be converted to `match_service_handle_t`s to be passed to `queue_policy` calls).  Here's a compilation error demonstrating this problem:
```c++
qmanager/policies/queue_policy_bf_base_impl.hpp:197:40: error: invalid conversion from ‘void*’ to ‘Flux::resource_model::detail::sched_fluxion_resource_t*’ 
```

Should I go ahead and modify the various functions in qmanager policies, or should I pursue a different approach?

2021-12-09 07:47 UTC, milroy commented
> It was there in the beginning, but with the introduction of an additional derived class, I am concerned about the use of void * reapi_t : void *. The intention was to pass an external arbitrary handle (e.g., flux_t *) into each API implementation. But void * can quickly become unwieldy with multiple class derivations. For this round, I believe we should at least introduce an abstract class support to avoid the use of void *. For example,

During the discussion with @dongahn today, we decided to delay implementing this item to a future PR.  It requires more thought and potentially restructuring some of qmanager.

I've made the requested updates to this PR; it's ready for another review @dongahn.

2022-01-06 17:40 UTC, milroy commented
I dropped the WIP title to indicate that the PR has been tested pretty thoroughly by me and @cmisale and should be ready for a final review.

2022-01-10 17:16 UTC, dongahn commented
Awesome! I will take a look.

2022-01-11 02:31 UTC, dongahn requested changes
Looks pretty good. But I think I have found some minor issues. Some of the issues are hard to catch without actual test cases (which I know you and Abhik are planning as part of a future PR). But at least, could you run valgrrid memcheck since I think I have found bunch of memory leaks and we want to make sure we don't have any apparent memory problems before this gets merged in.

2022-01-11 02:31 UTC, dongahn commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +    delete ctx;
Don't we now delete `ctx->rqt` as well?

2022-01-11 02:31 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +                    *(static_cast<resource_context_t * *>(h));
At first glance, this can be unsafe as you are relying on the actual memory layout. Can the caller actually pass the resource context instead of its containing struct pointer?

2022-01-11 02:31 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +                    *(static_cast<resource_context_t * *>(h));
Same as my comment for `match_allocate`

2022-01-11 02:31 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +static int remove_job (resource_context_t * &resource_ctx, uint64_t jobid)
Can this be a private member of the containing class for better isolation?

2022-01-11 02:31 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi.hpp
> +                     std::string &mode, bool &reserved, int64_t &at,
`mode` will hold a return value? If so, perhaps the inline doc can have that described.

2022-01-11 02:31 UTC, dongahn commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +        ctx->err_msg = __FUNCTION__;
`errno = ENOMEM` FWIW.

2022-01-14 01:59 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.h
> +char *reapi_cli_get_err_msg (reapi_cli_ctx_t *ctx);
Good catch!

2022-01-14 02:01 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +            json_decref (tmp_json);
Thanks for catching this!

2022-01-14 02:05 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        // No need for check here; returns 0 on failure
`josn_integer_value` returns the integer value, or 0 if `tmp_json` is not a JSON integer: https://jansson.readthedocs.io/en/2.11/apiref.html#c.json_integer_value

2022-01-14 02:07 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        // No need for check here; returns 0 on failure
of course, 0 can also be a valid JSON integer value...

2022-01-14 03:04 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        this->resource_ctx = nullptr;
The intention behind this was to catch the `nullptr` after the failed initialization:  https://github.com/flux-framework/flux-sched/blob/d23bd11f16f9939e4ecc69911066ee7cbec40dbb/resource/hlapi/bindings/c/reapi_cli.cpp#L78
I can add a `delete` if the condition is caught. Then is probably no reason for these checks: https://github.com/flux-framework/flux-sched/blob/d23bd11f16f9939e4ecc69911066ee7cbec40dbb/resource/hlapi/bindings/c/reapi_cli.cpp#L100

Another approach would be to delete `resource_ctx` immediately (i.e., at lines like 357 above) and throw an exception that will be caught by the caller.  I'm not sure which is the better approach. Do you have a preference @dongahn?

2022-01-14 03:09 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +        ctx->err_msg += "Error allocating memory: " + std::string (e.what ())
Thanks for catching this!

2022-01-14 03:09 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +                    *(static_cast<resource_context_t * *>(h));
Won't this require reworking the functions so they don't take `void *` as the first argument? That appears to get us back to another version of this discussion above: https://github.com/flux-framework/flux-sched/pull/888#issuecomment-989595644

2022-01-14 03:55 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        this->resource_ctx = nullptr;
You may be familiar with RAII: https://en.cppreference.com/w/cpp/language/raii

My preference is an object gets all the resources in the constructor orelse an error. That typically leads to a much better design when the object is composed with other subsystems like STL containers.

If an exception raising class isn't working for this case, I would treat the resource allocation needed for both the parent (`resource_ctx`) and a child (`resource_ctx->db`) a transaction.

2022-01-14 03:57 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        this->resource_ctx = nullptr;
Is this (https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#e6-use-raii-to-prevent-leaks) useful at all?

2022-01-14 04:08 UTC, milroy commented on resource/hlapi/bindings/c++/reapi.hpp
> +                     std::string &mode, bool &reserved, int64_t &at,
Yes, I'll add a description.

2022-01-14 06:44 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        this->resource_ctx = nullptr;
I was familiar with RAII and was considering how to implement it correctly here.  The link you provided is very helpful; it looks like throwing errors in the `resource_query_t` constructor and using a `std::unique_ptr` for `resource_ctx` is a good approach.  Thanks!

2022-01-14 06:58 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +                    *(static_cast<resource_context_t * *>(h));
Well, I guess my question is if it is safe to pass `ctx->rqt` (which is `resource_query_t *`) to `void *` and cast it back to `resource_context_t *`.  

```suggestion
    resource_query_t *query = static_cast<resource_query_t *> (h);
```

And then directly use `query` as a handle to get to other state?  

As is, I can't follow the code sorry.

2022-01-14 08:13 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +                    *(static_cast<resource_context_t * *>(h));
Oh, I understand what you mean now.  

Yes, I confess I never understood `*(static_cast<resource_context_t * *>(h))`, but we somehow got that to work in an hour-long hackathon.

2022-01-14 08:37 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +static int remove_job (resource_context_t * &resource_ctx, uint64_t jobid)
Yes, that will be much cleaner.

2022-01-15 08:34 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +    return strdup (err_buf.c_str ());
It turns out that if I don't use `strdup` the returned string is `""`.

2022-01-15 18:12 UTC, dongahn commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +    return strdup (err_buf.c_str ());
Hmmm, is that still the case when you have `const char *` as the return type of the function?

2022-01-16 00:58 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +    return strdup (err_buf.c_str ());
Yes, it's still the case when the return type is `const char *`.

2022-01-16 07:18 UTC, milroy commented on resource/hlapi/bindings/c/reapi_cli.cpp
> +    ctx->err_msg = "";
There are some events in the C API that can lead to errors that won't be captured if we don't have an `err_msg` for the C API, though.  E.g.: https://github.com/flux-framework/flux-sched/blob/b6f1f41a67b4a0bbcc42ec7f9ef675e632aea73c/resource/hlapi/bindings/c/reapi_cli.cpp#L79
and the following code.

2022-01-16 07:30 UTC, milroy commented
@dongahn thank you for the thorough review of the code and your helpful edits and suggestions!

Based on our discussions, I've made what I think to be substantial improvements to the PR.  In particular, I've collected everything `resource_ctx`-related into the `resource_query_t` class since that seemed to be an unnecessary and complicating distinction.  Together with limiting access to private class variables through getters and setters this makes the class easier to initialize and use.

Apart from a couple of questions related to your last review, this PR is ready for another look @dongahn.

2022-01-24 23:43 UTC, dongahn approved these changes
@milroy: This looks really good! Thank you for this importatn PR. I just added a comment for one minor issue about a jobid type conversion. Please put MWP when you are ready with this PR.

2022-01-24 23:43 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc = traverser->remove ((int64_t)jobid)) == 0) {
Minor issue: traverser class uses `int64_t` for jobid and for a very rare case, this conversion can be a problem. I'd suggest:

```suggestion
    if (jobid > std::numeric_limits<int64_t>::max) {
        errno = EOVERFLOW;
        return rc;
    }
    if ((rc = traverser->remove (static_cast<int64_t>(jobid)) == 0) {

2022-01-25 00:26 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc = traverser->remove ((int64_t)jobid)) == 0) {
Great catch, thanks!

2022-01-25 01:39 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc = traverser->remove ((int64_t)jobid)) == 0) {
I'm going to leave this line as is:
```C++
    if ((rc = traverser->remove ((int64_t)jobid)) == 0) {
```
since changing it to:
```C++
    if ((rc = traverser->remove (static_cast<int64_t>(jobid)) == 0) {
```
results in a compilation error:
```sh
error: init-statement in selection statements only available with ‘-std=c++17’ or ‘-std=gnu++17
```

2022-01-25 02:14 UTC, dongahn commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc = traverser->remove ((int64_t)jobid)) == 0) {
Ugg. Alternatively, you can

```c++
rc = traverser->remove (static_cast<int64_t>(jobid);
if ( rc == 0) {
```

2022-01-25 04:49 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +    if ((rc = traverser->remove ((int64_t)jobid)) == 0) {
Ok, it's fixed if I pull the `rc` assignment out of the `if` statement.

2022-01-25 04:53 UTC, milroy commented
> @milroy: This looks really good! Thank you for this importatn PR. I just added a comment for one minor issue about a jobid type conversion. Please put MWP when you are ready with this PR.

Thanks a lot @dongahn for the detailed reviews and the help restructuring the PR!  I made the final change you suggested and will set MWP.

2022-01-25 05:07 UTC, merged