Introduce multilevel ID match policy support
flux-framework/flux-sched pull request #895
Opened 2021-12-03 06:52 UTC by dongahn

This PR adds multilevel ID match policy support.

Fluxion currently have no match policy that can apply
higher level resource locality constraints for a Jobspec
that does not specify corresponding higher level resource
constraints: for example, `slot[4]->core[2]` as opposed to
`node[2]->slot[2]->core[2]`. The net effect is
a unconstrained jobspec can be scheduled
across many compute nodes without having to pack 
each of them. This will be unacceptable for many cases
including our upcoming node-exclusive scheduling.

- Introduce a configurable multilevel ID-based
  match policy class, which selects each resource
  using a user-defined function of numeric IDs;
  of their containing high-level resources and of itself;

- Refactor the existing `low` and `high` ID first policy
  classes to be aliases to this class to reduce duplicate
  codes;

- Add new node-locality-aware match policies using
  the multilevel id match policy class as well;

- Wire this into `resource-query` for testing;

- Extend `t3001-resource-basic.t` to make sure
   new policies are identical to `low`/`high` when scheduling
   unconstrained jobspecs as well as to add two
   basic smoke tests.

- Add `t3032-resource-node-locality.t` to test
   those cases where `hi|lonode` policies behave
   differently from `high`/`low` policies.

- Finally, add node locality semantics to first match
  to make its node selection less surprising. 

Resolve #720 and #894.

2021-12-03 18:39 UTC, dongahn commented
@tpatki, @milroy and @grondo: this should be ready for your review -- whoever is available :-)

2021-12-04 23:27 UTC, milroy requested changes
This PR looks great!  I found a few minor nits, and added some suggestions for clarifying documentation as well as an (optional) additional test.

2021-12-04 23:27 UTC, milroy commented on resource/policies/dfu_match_policy_factory.cpp
> +            ptr->add_score_factor (std::string ("node"), 1, 1000);
Similar to before: why is the multiplication factor 1000 here?

2021-12-04 23:27 UTC, milroy commented on t/t3032-resource-node-locality.t
> +#         slot[2]->core[2].
Is it worthwhile to add a test to ensure `hinode` differs from `high` by comparing the output of `hinode` with jobspec `node_locality/test001.yaml` with `high` using a modified version of `node_locality/test001.yaml` with a node-level constraint?  In short, using a `test_expect_failure` comparing their outputs?

2021-12-30 19:28 UTC, dongahn commented on resource/policies/dfu_match_multilevel_id.hpp
> +                          unsigned add_by, unsigned multiple_by);
Will change!

2021-12-30 23:01 UTC, dongahn commented on resource/policies/dfu_match_multilevel_id.hpp
> +        unsigned int m_add_by = 1;
`m_add_by=1` was chosen so that we can adjust 0-lowest ID space to 1-based ID space by default. Now that I think about this, it would be clearer to default it to 0 and then set it to 1 at the upper level. Will change.

2021-12-30 23:17 UTC, dongahn commented on resource/policies/dfu_match_multilevel_id_impl.hpp
> +    prefix = calc_multilevel_scores ();
Exactly! 

This way,  you can correctly scale the score of the visiting vertex as a function of all of the ancestor vertices (which ancestors will be used here are also programmable via `m_multilevel_factors`).

2021-12-30 23:34 UTC, dongahn commented on resource/policies/dfu_match_policy_factory.cpp
> +            ptr->add_score_factor (std::string ("node"), 1, 1000);
*_NODE_FIRST policies are such that we want to make compute node IDs take precedence over the IDs of any other node-local resource type (core, gpu, socket...) in setting our best match preference. 

Integer `1000` was chosen a bit arbitrarily. But the thought is it should be bigger than the largest ID of any node-local resource type.

Here, `1000` is essentially a scaling factor for the ID of each compute node: each compute node will contribute the prefix score equal to 1000 * (compute node ID + 1) to any of its node-local resource. For example, a core vertex ID (say coreID) on compute node 0 will end up being scored as 1000 + coreID while the same core vertex ID on compute node 1 will be scored as 2000 + coreID. And coreID would be greater than 0 and less than 1000 for a foreseeable future.

This way,  the compute node ID will be considered first even when the job spec doesn't specify a compute (`slot[2]->core[48]` as opposed to `node[2]->slot[1]->core[48]`).

Make sense?

2021-12-30 23:34 UTC, dongahn commented on resource/policies/dfu_match_policy_factory.cpp
> +            ptr->add_score_factor (std::string ("node"), 1, 1000);
Same answer as above.

2021-12-30 23:51 UTC, dongahn commented on t/t3032-resource-node-locality.t
> +#         slot[2]->core[2].
Great question!

`t3001-resource-basic.t` covers this to some extent. You will see `cmds067` for `lonode` has its own golden answer where as `low` doesn't have that coverage. 

The main reason I didn't add this explicit negative coverage was because the match results of `low` and `high` policies on a spec like `slot[2]->core[2]` are not deterministic so not great from the testing comparison point of view. 

In fact, depending on how the memory is laid out, there is a super minor chance that the result of `low` could be the same as 'lonode`! I think it is at the mercy of `sort` method of STL under lots of ties...

2021-12-30 23:55 UTC, dongahn commented on resource/policies/dfu_match_multilevel_id_impl.hpp
> +            return -1;
Yes, this should be called once per type you want to program in a factory class. If you call it with the same time, you will get `errno=EEXIST` with -1 returned. (In-line documented in the  `dfu_match_multilevel_id.hpp`)

2022-01-01 20:35 UTC, dongahn commented
@milroy: I believe I addressed all of the required changed and I am adding MWP. I will probably need to give an explicit approval to merge it in though. Thanks!

2022-01-06 07:14 UTC, milroy commented
@dongahn sorry, I just noticed your comment.  LGTM; thanks for the changes and explanations!

2022-01-06 07:14 UTC, milroy approved these changes

2022-01-06 07:15 UTC, merged

2022-01-10 17:11 UTC, dongahn commented
Thanks @milroy !