Fix REAPI C++ bindings
flux-framework/flux-sched pull request #974
Opened 2022-09-21 01:28 UTC by tpatki

C++ bindings have an issue where match_allocate doesn't set allocation, reservation or job info correctly. This was done in the C bindings, which is not the right place for it.

2022-09-21 20:25 UTC, milroy requested changes
Thanks a lot for finding this problem and fixing it @tpatki! There are a few minor changes that need to be made but this looks great overall.

2022-09-21 20:25 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        if ((rc = gettimeofday (&end_time, NULL)) < 0) {
Nit: Fluxion uses a space between double open parentheses for conditionals.

```suggestion
        if ( (rc = gettimeofday (&end_time, NULL)) < 0) {
```

2022-09-21 20:25 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +        if (job_info == NULL) {
The original location wrapped this in a `try...catch`. The `make_shared` [documentation](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared) mentions that it: "may throw [std::bad_alloc] or any exception thrown by the constructor of T. If an exception is thrown, the functions have no effect." I like the check for `NULL` since that appears to handle more potential failure modes. However, I think it's better to check for `nullptr`:

```suggestion
        if (job_info == nullptr) {
````

2022-09-21 20:25 UTC, milroy commented on resource/hlapi/bindings/c++/reapi_cli_impl.hpp
> +
Since this PR is already an API fixup, perhaps we can address a potentially small problem here. I think it's better to end the top-level `try...catch` block between the `if (rq->get_traverser_err_msg () != "") {` block and the `if ( (rc = rq->writers->emit (o)) < 0) {` block.

What do you think @tpatki?

2022-09-26 21:22 UTC, tpatki commented
@milroy I incorporated all the changes you had requested. I believe this is ready to go.

2022-09-26 22:26 UTC, jameshcorbett approved these changes
Looks reasonable to me.

2022-09-27 05:22 UTC, milroy commented
The changes look good. Thanks again @tpatki for the quick fix! Setting MWP.

2022-09-27 05:22 UTC, merged